ccd-definition/CaseType.json
ccd-definition/UserProfile.json
e2e/config.js
e2e/fixtures/events/createClaim.js
e2e/pages/createClaim/claimantSolicitorOrganisation.page.js
e2e/pages/createClaim/createCase.page.js
e2e/pages/createClaim/defendantSolicitorOrganisation.page.js

Jira: https://tools.hmcts.net/jira/browse/CMC-1545
changes: remove damages claims from user names

refactor:remove damages claims from user names (cmc-1545)

---

ccd-definition/CaseEventToComplexTypes/AddOrAmendClaimDocuments.json
ccd-definition/CaseEventToComplexTypes/CreateClaim.json
ccd-definition/CaseEventToComplexTypes/NotifyDefendantOfClaimDetails.json
ccd-definition/CaseEventToFields/AddOrAmendClaimDocuments.json
ccd-definition/CaseEventToFields/CreateClaim.json
ccd-definition/CaseEventToFields/NotifyDefendantOfClaimDetails.json
ccd-definition/ComplexTypes/ServedDocumentFiles.json
e2e/api/steps.js
e2e/fixtures/events/addOrAmendClaimDocuments.js
e2e/fixtures/events/createClaim.js
e2e/pages/caseProceedsInCaseman/takeCaseOffline.page.js
e2e/pages/createClaim/uploadParticularsOfClaim.page.js

- updated particularsOfClaimDocument field type
- removed particularsOfClaimDocumentNew field
- added missing awaits for functional tests
```
[ ] Yes
[x] No
```

refactor: updated particularsOfClaimDocument field type

---

ccd-definition/CaseEventToFields/ClaimantResponse.json
ccd-definition/CaseEventToFields/DefendantResponse.json

https://tools.hmcts.net/jira/browse/CMC-1600
Mandatory non disclosure of electronic documents in dq
```
[ ] Yes
[x] No
```

fix: mandatory disclosure non elec docs (CMC-1600)

---

ccd-definition/CaseEventToFields/CreateClaim.json

https://tools.hmcts.net/jira/browse/CMC-1581
Mandatory brief details of claim
```
[ ] Yes
[x] No
```

fix: mandatory details of claim CMC-1581)

---

ccd-definition/CaseEventToComplexTypes/AddDefendantLitigationFriend.json
ccd-definition/CaseEventToFields/AddDefendantLitigationFriend.json

https://tools.hmcts.net/jira/browse/CMC-1594
Claimant -> Defendant
```
[ ] Yes
[x] No
```

fix: defendant text for lit friend (CMC-1594)

---

ccd-definition/CaseEvent/User/UserEvents.json

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/CMC-1573
Change description
Allowed case proceeds in caseman from case dismissed state
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
```

refactor: case proceeds offline event in dismissed state (CMC-1573)

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml

build: switched to latest XUI image

---

ccd-definition/CaseEvent/User/UserEvents.json
e2e/steps_file.js

https://tools.hmcts.net/jira/browse/CMC-1601
Changed text from 'Submit response' to 'Submit'
```
[ ] Yes
[x] No
```

CMC-1601: Update button wording

---

package.json

https://tools.hmcts.net/jira/browse/CMC-1487
```
[ ] Yes
[x] No
```

feat: updated crossbrowser script to run e2e tests (CMC-1487)

---

ccd-definition/SearchInputFields.json
ccd-definition/SearchResultFields.json
ccd-definition/WorkBasketInputFields.json
ccd-definition/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/CMC-1661
update case list screen to show more case details
```
[ ] Yes
[ ] No
```

feat:update case list screen to show more case details

---

Jenkinsfile_CNP
bin/create-github-release.sh

https://tools.hmcts.net/jira/browse/CMC-1656
- add prod definition file to github release
```
[ ] Yes
[x] No
```

feat: add prod definition file to github release (CMC-1656)

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/CaseField.json
ccd-definition/CaseTypeTab/PaymentHistory.json

CMC-1640
add payment history tab
```
[ ] Yes
[ ] No
```

feat:add payment history tab (CMC-1640)

---

e2e/fixtures/events/createClaim.js

fix: updated org ids in api tests

---

ccd-definition/AuthorisationCaseEvent/staff.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/AuthorisationCaseField/staff.json
ccd-definition/AuthorisationCaseState/staff.json
ccd-definition/AuthorisationCaseType/staff.json
ccd-definition/AuthorisationComplexType/staff.json
ccd-definition/CaseField.json
ccd-definition/CaseTypeTab/PaymentHistory.json
ccd-definition/SearchInputFields.json
ccd-definition/SearchResultFields.json
ccd-definition/WorkBasketInputFields.json
ccd-definition/WorkBasketResultFields.json

refactor: removed LiveFrom from definition

---

build.gradle

[CMC-1682](url)
clean dependencies to fix cve issue 

fix: clean up to fix cve issue (CMC-1682)

---

e2e/pages/createClaim/createCase.page.js
e2e/steps_file.js

fix: unstable test on create case screen

---

e2e/tests/crossBrowser_tests.js
package.json
saucelabs.conf.js

https://tools.hmcts.net/jira/browse/CMC-1487
Added separate test file to run e2e journey in single scenario for cross browser tests. Otherwise the tests gets separated which makes reports harder to read and causes tests to fail (case id is not passed between scenarios).
```
[ ] Yes
[x] No
```

build: cross browsers tests improvements

---

e2e/api/steps.js

https://tools.hmcts.net/jira/browse/CMC-1628
- Fixing API tests to work with change to https://github.com/hmcts/civil-service/pull/40
```
[ ] Yes
[x] No
```

refactor: fix api tests for standardisation of confirmation page (CMC-1628) (1/2)

---

ccd-definition/ComplexTypes/DQ/Hearing.json
ccd-definition/ComplexTypes/DQ/HearingSupportRequirements.json
ccd-definition/ComplexTypes/DQ/RequestedCourt.json
ccd-definition/FixedLists/FileDirectionsQuestionnaireConfirm.json
e2e/api/steps.js

https://tools.hmcts.net/jira/browse/CMC-1265
CCD content changes 
(1) File directions questionnaire
"Change ‘I confirm I’ve explained to my client…’ to
‘I confirm I have explained to my client(s)…’
(2) Availability
Change ‘Are there any days within the next 12 months when you, your client’s…’ to
‘Are there any days within the next 12 months when you, your client(s)….’"
(3) Court location code
Change ‘The claimant requested…’ to
‘The Claimant legal representative requested...;
(4) Hearing support requirements
Change ‘Select any support you, your client and…’ to
‘Select any support you, your client(s) and…’
```
[ ] Yes
[x] No
```

refactor: updated client -> client(s) (CMC-1265)

---

ccd-definition/ComplexTypes/DQ/Hearing.json
ccd-definition/ComplexTypes/DQ/HearingSupportRequirements.json
ccd-definition/ComplexTypes/DQ/RequestedCourt.json
ccd-definition/FixedLists/FileDirectionsQuestionnaireConfirm.json
e2e/api/steps.js

Reverts hmcts/civil-ccd-definition#122

Revert "refactor: updated client -> client(s) (CMC-1265)"

---

e2e/steps_file.js

https://tools.hmcts.net/jira/browse/CMC-1693
Removed submitted callback message assertion in e2e for defendant dq
```
[ ] Yes
[x] No
```

fix: removed test assertion to allow service merging (CMC-1693)

---

e2e/tests/api_test.js
e2e/tests/solicitorCreatesClaim_test.js

https://tools.hmcts.net/jira/browse/CMC-1631
```
[ ] Yes
[x] No
```

fix: standardisation of content (CMC-1631) (1/3)

---

e2e/api/steps.js
e2e/steps_file.js
e2e/tests/api_test.js
e2e/tests/solicitorCreatesClaim_test.js

https://tools.hmcts.net/jira/browse/CMC-1631
```
[ ] Yes
[x] No
```

fix: standardisation of content (CMC-1631) (3/3)

---

e2e/crossbrowser/supportedBrowsers.js
e2e/pages/caseView.page.js
e2e/pages/createClaim/createCase.page.js
e2e/pages/login.page.js
e2e/steps_file.js
e2e/tests/crossBrowser_test.js
e2e/tests/rpaHandoff_test.js
e2e/tests/solicitorCreatesClaim_test.js

https://tools.hmcts.net/jira/browse/CMC-1693
Disables tests in microsoft edge to solve 1.1
Fixes the following issues from [confluence](https://tools.hmcts.net/confluence/pages/viewpage.action?spaceKey=CU&title=Cross+Browser+Tests+Issues&__ncforminfo=nWl6zt-axg0DGnQVIPZkO6yEUcA9FpdwBJKSNjGdKwUGZalLHpMvkwX0IpnPw4bZNs3K1zeN3MvKnIrNOix2YQ==)
2.1 (also fixes 6.1, 7.1)
2.4 (also fixes 3.3, 5.2)
3.1
3.2 (also fixes 4.1, 5.1, 7.2)
```
[ ] Yes
[x] No
```

fix: addressed xbrowser issues (CMC-1693)

---

ccd-definition/CaseField.json

https://tools.hmcts.net/jira/browse/CMC-1629
```
[ ] Yes
[x] No
```

fix: acknowledge claim loses defendant address (CMC-1629) 1/3

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/CMC-1629
```
[ ] Yes
[x] No
```

fix: added missing permissions (CMC-1692)

---

codecept.conf.js
e2e/steps_file.js

fix: added missing wait for retryUntilUrlChanges method

---

ccd-definition/AuthorisationCaseEvent/systemUpdate.json
ccd-definition/CaseEvent/Camunda/RoboticsEvents.json

[CMC-1611](https://tools.hmcts.net/jira/browse/CMC-1611)
add rpa continuous feed event 

feat: add rpa continuous feed event (CMC-1611)

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CMC-1680
```
[ ] Yes
[x] No
```

build: added uploading CCD definition on demo (CMC-1680)

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CMC-1680
```
[ ] Yes
[x] No
```

fix: added pushing to demo from master (CMC-1680)

---

ccd-definition/AuthorisationComplexType/solicitor.json
ccd-definition/CaseEventToComplexTypes/CreateClaim.json
e2e/pages/createClaim/claimantSolicitorOrganisation.page.js

https://tools.hmcts.net/jira/browse/CMC-1059
Prepopulate claimant organisation
```
[ ] Yes
[x] No
```

feat: prepopulate claimant organisation (CMC-1059)

---

ccd-definition/AuthorisationComplexType/solicitor.json
ccd-definition/CaseEventToComplexTypes/CreateClaim.json
e2e/pages/createClaim/claimantSolicitorOrganisation.page.js

Reverts hmcts/civil-ccd-definition#157

Revert "feat: prepopulate claimant organisation (CMC-1059)"

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json

https://tools.hmcts.net/jira/browse/CMC-1663
Add D permissions for Litigation Friend fields
```
[ ] Yes
[x] No
```

fix: add delete permission for lit friend (CMC-1663)

---

charts/civil-ccd/values.preview.template.yaml

N/A
Update param to be in line with latest ccd data store changes:
https://github.com/hmcts/ccd-data-store-api/commit/7aaea598ec77a756df825631d157ab41080b32b1#diff-dbe96111edf9ed265da7934c3918cc9088ee33549110c9ba95d7c418e4748086R64
```
[ ] Yes
[x] No
```

Update param to be in line with latest ccd data store changes

---

ccd-definition/CaseEventToFields/ClaimantResponse.json
ccd-definition/CaseEventToFields/DefendantResponse.json

[CMC1732](url)
Retain hidden values of allocatedTrack and claimType

fix: retain hidden values (CMC1732)

---

.dependabot/config.yml

N/A
- Changing depandabot to update weekly rather than daily, using less PR resources
```
[ ] Yes
[x] No
```

fix: change dependabot to update weekly

---

README.md

Adds some setup description to the README
```
[ ] Yes
[x] No
```

fix: Add API test setup to README (CMC-1728)

---

charts/civil-ccd/Chart.yaml
package.json
yarn.lock

N/A
- Bump java chart version to 3.6.0 
```
[] Yes
[x] No
```

build: bump java charts to 3.6.0

---

e2e/tests/api_test.js
e2e/tests/crossBrowser_test.js
e2e/tests/rpaHandoff_test.js
e2e/tests/smoke_test.js
e2e/tests/solicitorCreatesClaim_test.js
package.json
yarn.lock

n/a
Bumped codeceptjs framework version to 3.1.1
```
[ ] Yes
[x] No
```

fix: axios vulnerability, bumped codeceptjs to 3.1.1 (CMC-NA)

---

e2e/pages/caseProceedsInCaseman/caseProceedsInCaseman.page.js

https://tools.hmcts.net/jira/browse/CMC-1713
Fix RPA e2e test for nightly pipeline
```
[ ] Yes
[X] No
```

fix: amend RPA test date field (CMC-1713)

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/AuthorisationCaseField/staff.json
ccd-definition/CaseField.json

[CMC-1744](url)
add new timestamp for lit friend event 

feat: add new timestamp for lit friend event (CMC-1744)

---

e2e/pages/login.page.js
e2e/steps_file.js
e2e/tests/smoke_test.js

https://tools.hmcts.net/jira/browse/CMC-1713
Add retries to login to stop smoke test and full functional test failures
```
[ ] Yes
[X] No
```

Add retries to login section of e2e (CMC-1713)

---

e2e/tests/solicitorCreatesClaim_test.js

https://tools.hmcts.net/jira/browse/CMC-1713
Add retries to scenarios
```
[ ] Yes
[X] No
```

CMC-1713: add retries to scenarios

---

package.json
yarn.lock

N/A
Upgrade to codeceptjs v3.1.2
```
[ ] Yes
[X] No
```

Chore: Upgraded to lastest codeceptjs version

---

package.json
yarn.lock

N/A
Upgrade Husky from 4.2.5 to 7.0.2 due to potential security vulnerability
```
[ ] Yes
[X] No
```

chore: upgrade husky to latest version

---

config/owasp/suppressions.xml
e2e/api/steps.js
e2e/api/testingSupport.js
e2e/fixtures/events/addOrAmendClaimDocuments.js
e2e/fixtures/events/claimantResponse.js
e2e/fixtures/events/createClaim.js
e2e/fixtures/events/defendantResponse.js

https://tools.hmcts.net/jira/browse/CMC-1713
Fix nightly pipeline
```
[ ] Yes
[X] No
```

Chore: Fix nightly pipeline (CMC-1713)

---

e2e/pages/createClaim/claimantSolicitorOrganisation.page.js

N/A
Fix Test
```
[ ] Yes
[ ] No
```

Chore: Fix test

---

e2e/tests/rpaHandoff_test.js

Reinstate tests

---

e2e/tests/rpaHandoff_test.js

N/A
Add retries for RPA tests
```
[ ] Yes
[ X] No
```

Chore: add retry for RPA test to increase probability of green pipeline build

---

bin/utils/ccd-add-role.sh
charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.preview.template.yaml
codecept.conf.js

N/A
Fix pipeline for access management
```
[ ] Yes
[X] No
```

Chore: fix pipeline for access management

---

bin/utils/ccd-add-role.sh
charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
codecept.conf.js

N/A
Add access management config for master pipeline: aat/staging env
```
[ ] Yes
[x] No
```

Chore: fix civil ccd master pipeline

---

bin/utils/ccd-add-role.sh

testing if username for add_roles is the issue on master pipeline

---

bin/utils/ccd-add-role.sh
codecept.conf.js

Configurer on master test

---

ccd-definition/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/CMC-1848
Changed wording from respondent to defendant in summary page
```
[ ] Yes
[x] No
```

CMC-1848: Changed respondent to defendant on summary

---

bin/build-release-ccd-definition.sh
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
ccd-definition/AuthorisationCaseEvent/staffGAspec.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
ccd-definition/AuthorisationCaseField/caseAccessAssignmentGAspec.json
ccd-definition/AuthorisationCaseField/staffGAspec.json
ccd-definition/AuthorisationCaseField/systemUpdateGAspec.json
ccd-definition/AuthorisationComplexType/solicitorGAspec.json
ccd-definition/CaseEvent/User/UserEventsGAspec.json
ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/DQ/GeneralApplicationTypesGAspec.json
ccd-definition/ComplexTypes/GARespondentAgreementGAspec.json
ccd-definition/ComplexTypes/GATypeGAspec.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
ccd-definition/ComplexTypes/StatementOfTruthGAspec.json
ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
ccd-definition/FixedLists/StatementOfTruthConsentGAspec.json

General Application Screens - Initiate the general application creation.
```
[ ] Yes
[x] No
```

General Application Screens Feature/civ-65

---

Jenkinsfile_CNP
bin/utils/ccd-add-role.sh

N/A
Fix PR Pipeline for repo
```
[ ] Yes
[x] No
```

Chore: fix pipeline

---

Jenkinsfile_CNP
codecept.conf.js

N/A
Change in secret name
```
[ ] Yes
[ x] No
```

Chore: change in secret name

---

Jenkinsfile_CNP

Reverts hmcts/civil-ccd-definition#321

Revert "Chore/change to secret name"

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
ccd-definition/AuthorisationCaseField/staffGAspec.json
ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/StatementOfTruthGAspec.json

https://tools.hmcts.net/jira/browse/CIV-70
Create Textbox and Upload button for applicant to enter the evidence data and supporting document in Statement of Truth screen.
```
[ ] Yes
[x] No
```

Statement of Truth Screen - Enter evidence data

---

Jenkinsfile_CNP

N/A
Fixing pipeline
```
[ ] Yes
[ ] No
```

Chore: fixing pipeline

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseAdmitPartLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json

https://tools.hmcts.net/jira/browse/CIV-233
The PR consists of adding a new page to give the reason for why defendent cannot pay immediately.
```
[ ] Yes
[x] No
```

CIV-233 Adding New Page for Giving Reason Why Not Pay

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
ccd-definition/AuthorisationCaseField/caseAccessAssignmentGAspec.json
ccd-definition/AuthorisationCaseField/staffGAspec.json
ccd-definition/AuthorisationCaseField/systemUpdateGAspec.json
ccd-definition/AuthorisationComplexType/solicitorGAspec.json
ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAPBADetailsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-71
General Application Creation : Screen 7 : PBA Screen
```
[ ] Yes
[X] No
```

General Application Creation : PBA Screen - Feature/civ 71

---

e2e/pages/informAgreedExtensionDate/date.page.js

N/A
Fix e2e test for PRs
```
[ ] Yes
[x ] No
```

Chore: fix e2e test

---

ccd-definition/CaseEventToFields/CreateClaim.json

https://tools.hmcts.net/jira/browse/CMC-1874
```
[ ] Yes
[ ] No
```

cmc 1874 - remove org whitelisting

---

ccd-definition/CaseEventToComplexTypes/DefendantResponseLRspec.json
ccd-definition/ComplexTypes/DQ/1_SmallClaimUnavailableDateLRspec.json
ccd-definition/ComplexTypes/DQ/SmallClaimHearingLRspec.json

https://tools.hmcts.net/jira/browse/CIV-193
Case differences between ccd and service meant backend wasn't getting the values from frontend
```
[ ] Yes
[X] No
```

feat/CIV-193 fixed, small claims hearing screen

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
ccd-definition/CaseEvent/Camunda/BusinessProcessEventsGAspec.json
ccd-definition/CaseEvent/User/UserEventsGAspec.json

update civil-systemupdate permission

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
ccd-definition/AuthorisationCaseField/staffGAspec.json
ccd-definition/AuthorisationCaseField/systemUpdateGAspec.json
ccd-definition/AuthorisationComplexType/solicitorGAspec.json
ccd-definition/CaseEvent/User/UserEventsGAspec.json
ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
ccd-definition/ComplexTypes/GAStatementOfTruthGAspec.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
ccd-definition/FixedLists/GAHearingDurationGAspec.json

https://tools.hmcts.net/jira/browse/CIV-659
1. civil-ccd-definition : Add required fields under ccd-definition/ComplexTypes/GeneralApplicationGAspec.json to be able to capture all individual details per screen (done)
2. civil-ccd-definition : Add businessProcess (done)
3. civil-ccd-definition : Add a CallBackURLAboutToSubmitEvent for CaseEvent INITIATE_GENERAL_APPLICATION in UserEventsGAspec.json (done)
4. civil-ccd-definition : Add a fields under ccd-definition/ComplexTypes/GeneralApplicationGAspec.json to indicate whether the parent claim is multiparty or not (done)
```
[ ] Yes
[X] No
```

CIV-659 On about-to-submit for General Application Initiation

---

bin/utils/process-definition.sh
bin/variables/load-aat-environment-variables.sh
bin/variables/load-demo-environment-variables.sh
bin/variables/load-preview-environment-variables.sh
bin/variables/load-prod-environment-variables.sh
bin/variables/load-staging-environment-variables.sh
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
ccd-definition/CaseEvent/Camunda/BusinessProcessEventsGAspec.json
ccd-definition/CaseEvent/User/UserEventsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-877
Add back the BusinessProcessEventsGAspec.json with events specific to General Applications. Add on-submit callback for INITIATE_GENERAL_APPLICATION
The new events that are defined in the BusinessProcessEventsGAspec are not appearing (as expected) in the main menu as could be seen below:
```
[ ] Yes
[X] No
```

CIV-877 CCD changes for CIV-660

---

codecept.conf.js
e2e/pages/generalApplication/applicationDetails.page.js
e2e/pages/generalApplication/applicationType.page.js
e2e/pages/generalApplication/consentCheck.page.js
e2e/pages/generalApplication/gaPBANumber.page.js
e2e/pages/generalApplication/hearingDetails.page.js
e2e/pages/generalApplication/urgencyCheck.page.js
e2e/pages/generalApplication/withOutNotice.page.js
e2e/steps_file.js
e2e/tests/gaSpec/generalApplication_test.js
package.json

General apps test e2e functionality

Civ 736 (#381)

---

ccd-definition/CaseTypeTab/ClaimDetails.json

https://tools.hmcts.net/jira/browse/CMC-1901
```
[ ] Yes
[ ] No
```

show respondent2 details in claim details tab

---

ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/ComplexTypes/GARespondentAgreementGAspec.json
ccd-definition/ComplexTypes/GAUrgencyRecordGAspec.json
ccd-definition/ComplexTypes/GAWithOrWithoutNotice.json
ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
e2e/fragments/event.js
e2e/pages/caseView.page.js
e2e/pages/generalApplication/applicationType.page.js
e2e/steps_file.js
e2e/tests/gaSpec/generalApplication_test.js
e2e/tests/lrspec/solicitorCreatesClaim-LRspec_test.js

https://tools.hmcts.net/jira/browse/CIV-708
https://tools.hmcts.net/jira/browse/CIV-720
https://tools.hmcts.net/jira/browse/CIV-723
https://tools.hmcts.net/jira/browse/CIV-726
CIV-708 : With Notice Question Screen --> Added restriction on the textarea for 400 characters.
CIV-720 : Type of Application --> Removed the extra type of application since it is not going to be part of R1.
CIV-723 : Urgent Screen --> Added restriction on the textarea for 400 characters. We still need to have check on past-date through callback
CIV-726 : Consent Screen --> Removed full-stop in sentence end
```
[ ] Yes
[X] …
```

CIV-708-720-723-726 Fix typos and the extra type of application.

---

bin/build-release-ccd-definition.sh
ccd-definition/CaseField/CaseField-nonprod.json
ccd-definition/CaseField/CaseField-prod.json
ccd-definition/CaseField/CaseField.json

add new eligibility questions for multiparty

---

e2e/api/steps.js

N/A
Amend api test to work with new multiparty code
```
[ ] Yes
[X] No
```

Chore: Amend Defendant Response api test so as to work with multiparty

---

ccd-definition/CaseEvent/User/UserEvents.json

N/A
Point V1 callback to V0 in production
Linked to -> https://github.com/hmcts/civil-service/pull/584
```
[ ] Yes
[x] No
```

Move V1 callback to point to V0

---

ccd-definition/CaseEvent/User/UserEvents-nonprod.json
ccd-definition/CaseEvent/User/UserEvents-prod.json
ccd-definition/CaseEvent/User/UserEvents.json

related to https://github.com/hmcts/civil-service/pull/591
```
[ ] Yes
[ ] No
```

point prod to V0 callback

---

ccd-definition/CaseEventToFields/DefendantResponse-nonprod.json

https://tools.hmcts.net/jira/browse/CMC-1915
```
[ ] Yes
[ ] No
```

fix/1915: remove duplicate respondentDetails in defendant response journey

---

package.json
yarn.lock

N/A
security vulnerability
```
[ ] Yes
[X] No
```

upgrade mocha to alleviate nanoid vulnerability

---

package.json
yarn.lock

N/A
Upgrade node-fetch due to security vulnerability
```
[ ] Yes
[X] No
```

chore: upgrade node-fetch due to security vulnerability

---

ccd-definition/CaseEventToFields/DefendantResponse-nonprod.json

fix: show correct defendant reference in Respond to claim journey

---

ccd-definition/AuthorisationCaseType/AuthorisationCaseType.json

feat: unshuttering following multiparty release

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/CaseField/CaseField.json
ccd-definition/CaseTypeTab/Documents.json
ccd-definition/FixedLists/DocumentType.json

https://tools.hmcts.net/jira/browse/CMC-1907
Show uploaded documents in Claim Documents tab
```
[ ] Yes
[x] No
```

feat: show uploaded documents in Claim documents tab

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/CaseEventToFields/CreateSDO.json
ccd-definition/CaseField/CaseField.json
ccd-definition/FixedLists/OrderType.json

https://tools.hmcts.net/jira/browse/CIV-964
Third page in SDO judge journey
```
[ ] Yes
[x] No
```

Civ 964 judge order page

---

e2e/pages/informAgreedExtensionDate/date.page.js

N/A
Fix inform extension date
```
[ ] Yes
[X] No
```

Chore: fix date for inform agreed extension

---

ccd-definition/AuthorisationComplexType/solicitorGAspec.json
ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/ComplexTypes/1_UnavailableDatesGAspec.json
ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
ccd-definition/ComplexTypes/GAPBADetailsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-727
https://tools.hmcts.net/jira/browse/CIV-728
The PBA screen and Hearing Details screen changes.
```
[ ] Yes
[X] No
```

CIV-727 recovering PBA screen and Hearing details screen changes

---

.github/dependabot.yml

Updating dependabot so that it raises a maximum of 20 PRs at a time, once a week on Sunday night.
```
[ ] Yes
[ x] No
```

updating dependabot config

---

ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAStatementOfTruthGAspec.json

https://tools.hmcts.net/jira/browse/CIV-709
Screen shot is attached in comment's section.
Fields Validation for Request Order Without Consent Screen - Applicant Journey
```
[ ] Yes
[x] No
```

Field Validation

---

ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAPBADetailsGAspec.json
ccd-definition/ComplexTypes/GARespondentAgreementGAspec.json

https://tools.hmcts.net/jira/browse/CIV-729
Summary Screen field validation
```
[ ] Yes
[x] No
```

CIV-729 Summary Screen field validation

---

e2e/steps_file.js

To fix master build failures on smoke test

Increase xui page load timeout to 60

---

ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json

https://tools.hmcts.net/jira/browse/CIV-240
Showing proper information on the check answer page for defend all journey.
```
[ ] Yes
[X] No
```

change regarding the CIV-240 without useless local changes

---

ccd-definition/CaseField/CaseField.json

Reverts hmcts/civil-ccd-definition#466

Revert: "feat: remove hint text from defendant solicitor 1 and 2 search pages"

---

ccd-definition/ComplexTypes/GeneralApplicationGAspec.json

https://tools.hmcts.net/jira/browse/CIV-1273
Recovering lost changes
```
[ ] Yes
[X] No
```

CIV-1273 Notification claimant/defendant changes

---

ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec.json

Fix missing fields

---

ccd-definition/AuthorisationComplexType/solicitorGAspec.json
ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json
ccd-definition/ComplexTypes/1_GAPaymentDetailsGAspec.json
ccd-definition/ComplexTypes/GAPBADetailsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-951
The changes that were pushed as part of  https://github.com/hmcts/civil-ccd-definition/pull/514/files were lost. Introducing them again.
```
[ ] Yes
[X] No
```

CIV-951 Recover the lost Make Payment changes

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
ccd-definition/CaseEvent/Camunda/BusinessProcessEventsGAspec.json
ccd-definition/FixedLists/StatementOfTruthConsentGAspec.json

https://tools.hmcts.net/jira/browse/CIV-778
Move the END_BUSINESS_PROCESS_GASPEC from Civil CCD Def to GA CCD Def. Also add event UPDATE_CASE_WITH_GA_STATE to update state of GA in the parent case.
```
[ ] Yes
[X] No
```

Feature/civ-778_2 END_BUSINESS_PROCESS_GASPEC

---

Jenkinsfile_CNP
bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-1444

Update demo with latest config for PO's to test

---

codecept.conf.js
e2e/pages/selectSDO/allocateClaimType.page.js
e2e/pages/selectSDO/allocateSmallClaimsTrack.page.js
e2e/pages/selectSDO/sdoOrderType.page.js
e2e/pages/selectSDO/sumOfDamagesToBeDecided.page.js
e2e/steps_file.js
e2e/tests/sdo/sdo_journey_test.js
package.json

added the automation tests for SDO pages 1, 2 annd 3

---

Jenkinsfile_CNP
config/owasp/suppressions.xml

N/A
Fix Demo pipeline
```
[ ] Yes
[N] No
```

Chore: fix demo pipeline

---

build.gradle
config/owasp/suppressions.xml

N/A
Fix CVE failure
```
[ ] Yes
[X] No
```

Chore: fix CVE 2022-26336

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

N/A
CVE
```
[ ] Yes
[X] No
```

Chore: Fix CVE 2022-22965

---

ccd-definition/AuthorisationCaseEvent/systemUpdate.json
ccd-definition/CaseEvent/Camunda/NotificationEvents.json

https://tools.hmcts.net/jira/browse/CMC-1354
Add respondent 2 solicitor notification to claim dismiss
```
[ ] Yes
[x] No
```

feat: add event for NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_DISMISSED

---

ccd-definition/CaseEvent/Camunda/PaymentEvents.json

N/A
- Pointing V1 callback to V0 
-> Linked to PR https://github.com/hmcts/civil-service/pull/812
```
[ ] Yes
[x] No
```

refactor: point to V0 callback for PBA Payments (2/2)

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/CaseEventToFields/CreateClaim.json
ccd-definition/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/CMC-1991
Added a new flag 'claimStarted' to be used as a show condition to stop users being able to access mid case creation pages when previously entered data is missing.
```
[ ] Yes
[X] No
```

Added claimStarted field and PageShowCondition to non protected page fields

---

bin/build-release-ccd-definition.sh
package.json

New test1648 branch

---

build.gradle
e2e/pages/caseView.page.js
e2e/pages/respondToDefence/proceed.page.js
e2e/steps_file.js
e2e/tests/ui_tests/damages/rpaHandoff_test.js

https://tools.hmcts.net/jira/browse/CMC-2030
```
[ ] Yes
[X] No
```

Fix nightly tests

---

ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json

https://tools.hmcts.net/jira/browse/CIV-1976
https://github.com/hmcts/civil-service/pull/882
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/133
https://github.com/hmcts/civil-general-applications/pull/212
'Amend a stmt of case'. expand the word 'stmt' to 'statement'.
```
[ ] Yes
[ ] No
```

CIV-1976 Text Change

---

ccd-definition/CaseEventToComplexTypes/DefendantResponse.json
ccd-definition/CaseEventToComplexTypes/RespondToClaim.json

https://tools.hmcts.net/jira/browse/CMC-2000
- update statement of truth wording
```
[ ] Yes
[ ] No
```

CMC-2000 update statement of truth wording for defendant response

---

ccd-definition/FixedLists/RespondentResponseTypePaidStatusLRspec.json

Adding DID_NOT_PAY to correspond to civil-service CIV-2251 changes
```
[ ] Yes
[ ] No
```

Adding DID_NOT_PAY to correspond to civil-service CIV-2251 changes

---

ccd-definition/CaseEventToFields/DefendantResponseAdmitPartLRspec.json

Defectsfix

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json

https://tools.hmcts.net/jira/browse/CIV-2396
This PR contains the change on label in check your answer page for 2v1 case
```
[ ] Yes
[ ] No
```

CIV-2396: Update Check Your Answer Page

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json

https://tools.hmcts.net/jira/browse/CIV-2411
The PR contains the change for SOT page wordings change for claimant response
```
[ ] Yes
[ ] No
```

CIV-2411: I2P Incorrect Statement of Truth

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventLRspec.json
e2e/tests/ui_tests/lrspec/1v1CreateClaim-LRspec_test.js

Remove aos
```
[ ] Yes
[ ] No
```

Remove aos

---

e2e/fixtures/events/createClaimSpec.js

fixing api tests

---

ccd-definition/CaseEventToFields/ClaimantResponseLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json

civ-2446 - Experts screen

---

ccd-definition/CaseField/CaseFieldGAspec.json

https://tools.hmcts.net/jira/browse/CIV-2275
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/177
https://github.com/hmcts/civil-general-applications/pull/289
For Which Document dropdown - change Defense to Defence.
Add document types to upload files component text. To include doc, docx, dot, pdf, rtf, xlt or xlsx On Applicant Screen and Upload screens
```
[ ] Yes
[ ] No
```

Fix typo and add pdf types

---

build.gradle
ccd-definition/AuthorisationCaseType/AuthorisationCaseType.json
charts/civil-ccd/values.preview.template.yaml

Shutter LR and Damages
```
[ ] Yes
[ ] No
```

Shutter LR and Damages

---

ccd-definition/AuthorisationCaseType/AuthorisationCaseType.json

Unshutter applications
```
[ ] Yes
[ ] No
```

Unshutter applications

---

ccd-definition/AuthorisationCaseEvent/systemUpdateDJ.json
ccd-definition/CaseEvent/Camunda/NotificationEventsDJ.json

CIV-122 DJ Damages Notification

---

e2e/tests/api_tests/damages/api_1v1_test.js

N/A
Skip failing test until new ccd state is defined
```
[ ] Yes
[X] No
```

skip test until new state has been defined

---

ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec.json

https://tools.hmcts.net/jira/browse/CIV-2463
Refactor use of string on general app notification deadline
```
[ ] Yes
[x] No
```

CIV-2463 Refactor use of string on general app notification deadline

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-3020
```
[ ] Yes
[x] No
```

Config for judicial ref data

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json
ccd-definition/CaseEventToComplexTypes/CreateSDO-SDO-nonprod.json
ccd-definition/CaseEventToFields/CreateSDO-SDO-nonprod.json
ccd-definition/CaseField/CaseField-SDO-nonprod.json
ccd-definition/ComplexTypes/SmallClaimsCreditHire-SDO-nonprod.json
ccd-definition/ComplexTypes/SmallClaimsRoadTrafficAccident-SDO-nonprod.json
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CIV-1835
This PR adds additional directions fields (non populated for now, will come in a future PR) to sdo small claims page
```
[ ] Yes
[x] No
```

Civ 1835 small claims additional directions sdo final

---

.gitignore
Jenkinsfile_CNP
charts/civil-ccd/Chart.yaml
codecept.conf.js
e2e/config.js
package.json

To fix 
We have noticed deprecated configuration in HMCTS_a_to_c_Nightly/civil-service/master:
No functional test results found, make sure you have at least one created. 
This configuration will stop working by 30/06/2022 00:00 AM (in 2 days)

Update report folder structure

---

config/owasp/suppressions.xml

updated CVE
```
[ ] Yes
[ x] No
```

updated CVE

---

ccd-definition/CaseField/CaseField.json
ccd-definition/CaseField/CaseFieldLRspec.json

This PR contains change to fix the error in the camunda
```
[ ] Yes
[ ] No
```

Fix for civil-camunda error

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ.json
ccd-definition/CaseEventToComplexTypes/HearingRequirementsDJ.json
ccd-definition/CaseEventToFields/DefaultJudgmentDJ.json
ccd-definition/CaseField/CaseFieldDJ.json
ccd-definition/ComplexTypes/HearingRequirementsDJ.json
charts/civil-ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/CIV-2793
```
[ ] Yes
[ x ] No
```

CIV-2793 add case management location

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ.json
ccd-definition/CaseEventToFields/DefaultJudgmentDJ.json
ccd-definition/CaseField/CaseFieldDJ.json

Add location name

---

ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
ccd-definition/AuthorisationCaseField/caseAccessAssignmentGAspec.json
ccd-definition/AuthorisationCaseField/staffGAspec.json
ccd-definition/AuthorisationCaseField/systemUpdateGAspec.json
ccd-definition/CaseEvent/Camunda/CaseEvents.json
ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/CaseTypeTab/Documents.json
ccd-definition/FixedLists/DocumentType.json

Reverts hmcts/civil-ccd-definition#1007

Revert "Feature/civ 2631"

---

bin/add-roles.sh
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ.json
ccd-definition/AuthorisationCaseState/AuthorisationCaseState-nonprod.json
ccd-definition/AuthorisationCaseType/AuthorisationCaseType-nonprod.json
ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json
src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java

Reverts hmcts/civil-ccd-definition#1049

Revert "Feat/access profiles updates"

---

bin/add-roles.sh
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-SDO-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
ccd-definition/AuthorisationCaseState/AuthorisationCaseState-nonprod.json
ccd-definition/AuthorisationCaseState/approver.json
ccd-definition/AuthorisationCaseState/caseAccessAssignment.json
ccd-definition/AuthorisationCaseState/staff.json
ccd-definition/AuthorisationCaseState/systemUpdate.json
ccd-definition/AuthorisationCaseType/AuthorisationCaseType-nonprod.json
ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json
ccd-definition/State.json
src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java

https://tools.hmcts.net/jira/browse/CIV-1859
https://tools.hmcts.net/jira/browse/CIV-2454
This PR creates the `CASE_PROGRESSION` state and the `Legal-Adviser` access profile as well as a `hearing-centre-admin` role.
```
[ ] Yes
[x] No
```

create new state and role

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json

N/A
- Move LR `claimantCounterClaimLabel_2v1` from AuthorisationCaseField.json to AuthorisationCaseFieldLRspec.json
```
[ ] Yes
[x] No
```

refactor: Move LR AuthField from Base to LR File

---

ccd-definition/CaseEvent/User/UsersEventsDJ-SDO-nonprod.json
ccd-definition/CaseEventToFields/DefaultJudgmentDJ-SDO-nonprod.json

Changed label for DJ SDO event

---

ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAUrgencyRecordGAspec.json
ccd-definition/ComplexTypes/GAWithOrWithoutNotice.json
ccd-definition/FixedLists/StatementOfTruthConsentGAspec.json

The fix for CIV-3659 and CIV-3642 is combined together
https://tools.hmcts.net/jira/browse/CIV-3659
https://tools.hmcts.net/jira/browse/CIV-3642
1. Additional text require on Applicant Screens
2. Statement of Truth wording needs updating
```
[ ] Yes
[ ] No
```

CIV-3659-3642 Refactor display text

---

charts/civil-ccd/Chart.yaml

bump ccd chart to 8.0.17

---

ccd-definition/CaseEventToComplexTypes/CreateClaimCUI.json
ccd-definition/CaseEventToComplexTypes/CreateClaimLRspec.json
ccd-definition/ComplexTypes/Party.json

https://tools.hmcts.net/jira/browse/CIV-3660
This PR contains changes for adding a new email field to send email to respondent when there is no legal representative.
```
[ ] Yes
[ ] No
```

CIV-3660: Update for adding new email field

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

Map access profiles for specific and challenged access user roles
https://tools.hmcts.net/jira/browse/CIV-3845)
```
[ ] Yes
[ x] No
```

specific and challenged access profiles

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-4535
```
[ ] Yes
[ x] No
```

Addition of "senior-tribunal-caseworker"

---

bin/variables/load-staging-environment-variables.sh

Fix master pipeline

---

ccd-definition/CaseEventToFields/DefendantResponse.json

https://tools.hmcts.net/jira/browse/CIV-3992
- Added 'Part admission' to show upload defence file
```
[ ] Yes
[x] No
```

feat/civ-3992 Add defence document when part admission

---

Jenkinsfile_CNP

disable ssl n tests

---

bin/variables/load-prod-environment-variables.sh

use http instead of https for prod config

---

ccd-definition/CaseEvent/User/UserEvents-SDO-nonprod.json
ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

Events for ccd

---

ccd-definition/CaseEvent/User/UserEvents-SDO-nonprod.json
ccd-definition/CaseEventToFields/CreateSDO-SDO-nonprod.json
e2e/api/steps.js

https://tools.hmcts.net/jira/browse/CIV-3008
Prepopulation callback changed from Mid to About-To-Start to prevent it being called multiple times
```
[ ] Yes
[x] No
```

CIV - 3008 Prepopulation callback changed from Mid to About-To-Start

---

e2e/fixtures/events/createClaim.js

Fix Lip api test by removing respondent organisation policy
```
[ ] Yes
[x] No
```

fix api lip test by removing respondent organisation policy

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

addition of caseworker-caa to RoleToAccessProfiles-nonprod.json
```
[ ] Yes
[ x] No
```

addition of caseworker-caa to RoleToAccessProfiles-nonprod.json

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

added back senior-tribunal-caseworker role.
```
[ ] Yes
[X ] No
```

added back senior tribunal caseworker

---

build.gradle
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventDJ-SDO-nonprod.json
ccd-definition/CaseField/CaseFieldDJ-SDO-nonprod.json

Added authorisation for take case offline

---

ccd-definition/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/CIV-2155
```
[ ] Yes
[ ] No
```

feat: remove hint text from defendant solicitor 1 and 2 search pages

---

e2e/api/steps.js
e2e/fragments/dq/requestedCourt.page.js
e2e/pages/createClaim/chooseCourt.page.js

fix api and e2e test to add env check

---

e2e/api/steps.js
e2e/fragments/dq/requestedCourt.page.js
e2e/pages/createClaim/chooseCourt.page.js

N/A
Fix tests
```
[ ] Yes
[X] No
```

Fix court location issue add logging

---

charts/civil-ccd/values.preview.template.yaml

I see stitiching api is disabled in this repo, we need it to be enabled for testing

Enable stitching api in preivew.

---

e2e/api/steps.js

Fix Def org missing issue in tests

---

bin/add-roles.sh
e2e/config.js

N/A
Fix Typo
```
[ ] Yes
[X ] No
```

FIX: typo in add-roles.sh

---

e2e/api/steps.js

3521: fix test toggle to remove CAC field in aat

---

build.gradle

N/A
fix CVE-2022-38752
```
[ ] Yes
[X] No
```

FIX: CVE-2022-38752

---

e2e/fixtures/events/defaultJudgment1v2Spec.js
e2e/fixtures/events/defaultJudgment2v1Spec.js
e2e/fixtures/events/defaultJudgmentSpec.js

Update spec test with paymentTypeSelection

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ-SDO-HNL-nonprod.json
ccd-definition/CaseEventToComplexTypes/DefaultJudgmentDJ-SDO-HNL-nonprod.json
ccd-definition/CaseEventToFields/DefaultJudgmentDJ-SDO-HNL-nonprod.json
ccd-definition/CaseField/CaseFieldDJ-SDO-HNL-nonprod.json
ccd-definition/ComplexTypes/DefaultJudgmentSDO/DisposalHearingNotes-DJ-SDO-nonprod.json
ccd-definition/FixedLists/DisposalHearingBundleType-SDO-HNL-nonprod.json

Updating SDO-HNL-nonprod.json files to reflect changes in SDO-nonprod.json files
```
[ ] Yes
[ ] No
```

Updating SDO-HNL-nonprod.json files

---

build.gradle

*Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

Updated JacksonCVE-2022-42003

---

bin/build-release-ccd-definition.sh

N/A
- Removing spaces in CUI exclusions
```
[ ] Yes
[x] No
```

remove spaces in CUI exclusions

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
e2e/api/steps.js

Adding SDO related fields in non-prod files
```
[ ] Yes
[ x] No
```

Adding SDO related fields in non-prod files

---

ccd-definition/CaseEventToFields/ClaimantResponse-nonprod.json
ccd-definition/CaseEventToFields/ClaimantResponse-prod.json
ccd-definition/CaseEventToFields/ClaimantResponse.json
codecept.conf.js

Fixing caseevents to fields by moving them to nonprod files TEST

---

charts/civil-ccd/values.aat.template.yaml

https://tools.hmcts.net/jira/browse/CIV-5215
- Disable key vaults for camunda pod in staging env
```
[ ] Yes
[x] No
```

fix/CIV-5215: disable camunda keyvaults

---

charts/civil-ccd/Chart.yaml

Try latest idam-pr helm chart

---

build.gradle
config/owasp/suppressions.xml

CIV-4862
Fix CVE-2020-5421
```
[ ] Yes
[x] No
```

Fix CVE-2020-5421

---

.github/workflows/stale.yml

changing stale PR bot schedule
```
[ ] Yes
[x ] No
```

changing bot schedule

---

e2e/api/testingSupport.js

N/A
- Reduced attempt rate to limit the load on Camunda
- Reduced number of attempts to keep the same test running time in case of failure
```
[ ] Yes
[x] No
```

Tweak test retry parameters

---

ccd-definition/ComplexTypes/DQ/RequestedCourtLocationLRspec-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-5188
changed RequestedCourt label and hinttext
```
[ ] Yes
[x] No
```

CIV-5188 changed RequestedCourt label and hinttext

---

config/owasp/suppressions.xml

CIV-4846: 
CVE-2021-22053 from suppression
```
[ ] Yes
[x] No
```

CIV-4846: Remove CVE-2021-22053 from suppression

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json

Provide GS profile to to challenged and specific access roles

---

charts/civil-ccd/values.aat.template.yaml

https://tools.hmcts.net/jira/browse/CIV-1610
- Authorise AAC in XUI and CCD Data Store in Staging Environment
```
[ ] Yes
[x] No
```

fix/CIV-1610: Authorise AAC in Staging

---

ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json

https://tools.hmcts.net/jira/browse/CIV-5227
Make Hearing date optional
```
[ ] Yes
[ ] No
```

CIV-5227 Make hearing date optional

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CIV-4844

suppression file

---

ccd-definition/CaseEvent/Camunda/NotificationEventsDJ.json
ccd-definition/CaseEvent/User/UserEventsDJ.json
e2e/api/steps.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v2_test.js

Changed the State after the end of Camunda flow

---

e2e/tests/api_tests/defaultJudgments/api_dj_1v2_test.js

Changed assertion for Submitted event and block test

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#1447

Revert "Update exclusions"

---

ccd-definition/ComplexTypes/Party.json

https://tools.hmcts.net/jira/browse/CIV-5391
re-add the email
```
[ ] Yes
[ ] No
```

CIV-5391 re-add email field for lr claims

---

ccd-definition/ComplexTypes/Party.json

https://tools.hmcts.net/jira/browse/CIV-5391
revert the changes as it breaks the pipeline. there is another pr on its way that should fix the bug
```
[ ] Yes
[ ] No
```

Bug/civ 5391 revert re-adding of the email field

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-HNL-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/AuthorisationCaseField/staff-nonprod.json
ccd-definition/AuthorisationCaseField/staff.json

Moving unsuitableSDODate to non-prod files
```
[ ] Yes
[ x] No
```

Moving unsuitableSDODate to non-prod files

---

e2e/api/steps.js
e2e/api/steps_LRspec.js

Adding condition for State to Judicial Referral
```
[ ] Yes
[ ] No
```

Adding condition for State to Judicial Referral

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-HNL-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ-SDO-HNL-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ-SDO-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-5114
Change to authorisations to enable items to be removed from collection after being added
```
[ ] Yes
[ ] No
```

Fix for removing items from collection

---

.github/renovate.json

Upgrade helm charts  and gradlew through renovate

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-3601
```
[ ] Yes
[ ] No
```

CIV-3601 add variables for new send letter service and points to cui

---

Jenkinsfile_CNP

Move ccd definition creation ahead

---

ccd-definition/ComplexTypes/SdoOrderDocument-SDO-nonprod.json

Fixes SDO document_url key not specified

---

Dockerfile
Jenkinsfile_CNP

Disable docker steps as not needed.

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml

CIV-5447
Applying the same LD changes that have been applied to civil-service
```
[ ] Yes
[x] No
```

Harmonize LaunchDarkly with civil-service

---

charts/civil-ccd/values.aat.template.yaml

CIV-5447
```
[ ] Yes
[x] No
```

Fix LaunchDarkly config on AAT

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.yaml
config/owasp/suppressions.xml

Avoids issues like https://github.com/hmcts/civil-ccd-definition/commit/20bb89c69fee1830e8cb6ca53193ecddd0d6b8c1 causing issue on all PRs
```
[ ] Yes
[x] No
```

Move civil service as helm dependency

---

e2e/reporters/accessibility-reporter/resources/angular.min.js

[CIV-5855](https://tools.hmcts.net/jira/browse/CIV-5855)
Bump angular version to 1.8.0
```
[ ] Yes
[x] No
```

CIV-5855: Fix for CVE-2020-7676 

---

build.gradle
config/owasp/suppressions.xml

CIV-4840
```
[ ] Yes
[x] No
```

CIV-4840: Fix cve-2020-15250

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml
charts/civil-ccd/values.yaml

Currently entire chart config is duplicated across values.preview and values.aat, while the only difference being ingress mostly
```
[ ] Yes
[x] No
```

Clean up charts by removing duplications

---

charts/civil-ccd/values.template.yaml

Disable polling emitter

---

ccd-definition/CaseTypeTab/DefaultJudgmentDetailsDJ.json
ccd-definition/CaseTypeTab/DocumentsDJ.json
charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml
charts/civil-ccd/values.yaml
e2e/api/steps.js
e2e/api/steps_LRspec.js
e2e/fixtures/events/defendantResponseSpec1v2.js
src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java

Two Judgement tabs appearing for Spec + DJ claim
https://tools.hmcts.net/jira/browse/CIV-6022
```
[ ] Yes
[ ] No
```

Two Judgement tabs appearing for Spec + DJ claim

---

package.json
yarn.lock

N/A
Upgrade codeceptjs to latest version
```
[ ] Yes
[X] No
```

upgrade codeceptjs to fix setStatus error

---

ccd-definition/CaseEventToComplexTypes/DefaultJudgmentDJ-SDO-HNL-nonprod.json
ccd-definition/CaseEventToComplexTypes/DefaultJudgmentDJ-SDO-nonprod.json
ccd-definition/CaseField/CaseFieldDJ-SDO-HNL-nonprod.json
ccd-definition/CaseField/CaseFieldDJ-SDO-nonprod.json
ccd-definition/ComplexTypes/DefaultJudgmentSDO/DisposalHearingSchedulesOfLoss-DJ-nonprod.json

CIV-6173 Update disposal screens

---

src/main/java/uk/gov/hmcts/reform/civil/ccdvalidation/AuthorisationComplexTypeCCDValidator.java
src/test/java/uk/gov/hmcts/reform/civil/ccdvalidation/AuthorisationComplexTypeCCDValidatorTest.java

CIV-6301
Fixing a broken validator
```
[ ] Yes
[x] No
```

CIV-6301 Fixed test

---

e2e/helpers/hnlFeatureHelper.js

add party to test fixture

---

.gitignore
charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.template.yaml
charts/civil-ccd/values.yaml

[CIV-5967](https://tools.hmcts.net/jira/browse/CIV-5967)
Remove bitnami Dependency
```
[ ] Yes
[ ] No
```

CIV-5967 - Remove bitnami Dependency

---

charts/civil-ccd/values.template.yaml

N/A
Fix Postgres
```
[ ] Yes
[X] No
```

fix postgres for ccd master pipeline

---

ccd-definition/AuthorisationCaseType/AuthorisationCaseType.json
ccd-definition/AuthorisationCaseType/approver.json
ccd-definition/AuthorisationCaseType/caseAccessAssignment.json
ccd-definition/AuthorisationCaseType/staff.json
codecept.conf.js

Unshutter release and enable test cases

---

codecept.conf.js
config/owasp/suppressions.xml
e2e/pages/caseView.page.js
e2e/pages/createClaim/createCaseLRspec.page.js

Reverts hmcts/civil-ccd-definition#1942

Revert "unshutter release"

---

build.gradle
config/owasp/suppressions.xml
e2e/pages/createClaim/createCase.page.js
e2e/pages/createClaim/createCaseLRspec.page.js
e2e/steps_file.js

Update ccd Ft tests 

---

config/owasp/suppressions.xml

N/A
Temporarily suppress a vulnerability to allow builds to run
```
[ ] Yes
[x] No
```

Temporarily suppress CVE vulnerability

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CIV-6655
Fix to change civil service Url back for aat
```
[x] Yes
[] No
```

changed civil service URL back for AAT

---

Jenkinsfile_CNP
bin/variables/load-preview-environment-variables.sh
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml

Reverts hmcts/civil-ccd-definition#1974

Revert "Apply platform.hmcts.net URLs"

---

Jenkinsfile_CNP
charts/civil-ccd/values.template.yaml

CIV-6655
Updating URLs
```
[ ] Yes
[x] No
```

Updating URLs

---

Jenkinsfile_CNP
charts/civil-ccd/values.template.yaml

Reverts hmcts/civil-ccd-definition#2000

Revert "Updating URLs" and apply only one of its changes

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml

CIV-6655
Updating YAML files for URL changes
```
[ ] Yes
[x] No
```

Updating YAML files for URL changes

---

bin/variables/load-staging-environment-variables.sh

CIV-6655
Changing some other URLs we previously missed
```
[ ] Yes
[x] No
```

Changed some URLs we previously missed

---

ccd-definition/AuthorisationCaseType/AuthorisationCaseType.json
ccd-definition/AuthorisationCaseType/approver.json
ccd-definition/AuthorisationCaseType/caseAccessAssignment.json
ccd-definition/AuthorisationCaseType/staff.json
ccd-definition/AuthorisationCaseType/systemUpdate.json

Tech debt PR to combine AuthorisationCaseType files so that all users types are either contained in AuthorisationCaseType.json or AuthorisationCaseType-nonprod.json
```
[ ] Yes
[X] No
```

Combining AuthorisationCaseType Files

---

e2e/api/steps.js

CIV-2493
Isolated a change from sdo api tests so that it doesn't affer current tests
```
[ ] Yes
[X] No
```

CIV-2493 isolated create_sdo test changes from other tests' methods

---

charts/civil-ccd/Chart.yaml

ccd to 8.0.23

---

config/owasp/suppressions.xml

N/A
Adding suppression temporarily
```
[ ] Yes
[x] No
```

Adding suppression temporarily

---

Jenkinsfile_CNP

CIV-6644
Clear the pods regardless of success or failure
```
[ ] Yes
[x] No
```

Clear the pods regardless of success or failure

---

config/owasp/suppressions.xml

CIV-6930
Temporarily suppressing a new vulnerability to allow builds to progress
```
[ ] Yes
[x] No
```

CIV-6930 - Suppressing vulnerability temporarily

---

ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceDocumentType.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceExpert1-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceExpert2-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceExpert3-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceExpert4-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceWitness1-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceWitness2-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceWitness3-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-6765
Added createddatetime for all uploaded evidence
```
[ ] Yes
[ ] No
```

added created date for evidence upload files

---

Jenkinsfile_CNP

CIV-6948
Fix github deployment URL
```
[ ] Yes
[x] No
```

CIV-6948 - Fix github deployment URL

---

config/owasp/suppressions.xml

Adding Vulnerability suppression
```

Adding Vulnerability suppression

---

config/owasp/suppressions.xml

CIV-6909 Update suppressions.xml

---

ccd-definition/CaseEvent/Camunda/DocmosisEvents-nonprod.json
ccd-definition/CaseEvent/Camunda/DocmosisEvents-prod.json
ccd-definition/CaseEvent/Camunda/DocmosisEvents.json

Moving generate sealed form event to prod file so that CUI can amend it in its non-prod file.
```
[ ] Yes
[ x] No
```

Moving generate sealed form event to prod file 

---

e2e/fixtures/events/createSDO.js

CIV-2493
Update to match last sdo changes
```
[ ] Yes
[X] No
```

CIV-4302 added wa tests

---

ccd-definition/ComplexTypes/CaseLocation.json

Fix prod case location

---

e2e/tests/api_tests/sdo/sdo_test.js

CIV-6723
Moved some sdo tests to nightly build
```
[ ] Yes
[X] No
```

CIV-6723 moves some tests to night build

---

e2e/tests/api_tests/sdo/sdo_test.js

CIV-2493
Changed users from those to be used in local env to right ones for Jenkins build
```
[ ] Yes
[X] No
```

CIV-2493 using correct users for preview env

---

bin/build-release-ccd-definition.sh

CIV-5411 allowing ga r2 in demo

---

.dependabot/config.yml
.github/dependabot.yml
.github/renovate.json

https://tools.hmcts.net/jira/browse/CIV-7079
Dependabot removed and its tasks delegated to renovate
```
[ ] Yes
[x] No
```

CIV-7079 remove dependabot and delegate its tasks to renovate

---

ccd-definition/AuthorisationCaseField/StaffLRspec-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/SystemUpdateLRspec-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/staffLRspec-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec-CUI-nonprod.json

Fix incorrect case for StaffLRspec-CUI-nonprod.json and SystemUpdateLRspec-CUI-nonprod.json
```
[ ] Yes
[ ] No
```

CIV-5996 Fix incorrect case for ccd files

---

ccd-definition/CaseField/CaseFieldGAspec.json
ccd-definition/ComplexTypes/GAHearingDateGAspec.json

https://tools.hmcts.net/jira/browse/CIV-7026
Fix label issue for vary judgement
```
[ ] Yes
[ ] No
```

CIV-7026 Fix label for vary judgement

---

.github/CODEOWNERS

CIV-5433
Correct Code Owners
```
[ ] Yes
[ x ] No
```

CIV-5433 - Correct Code Owners

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/CIV-7193
Added back sunday weekly schedule and concurrency limit as previously done for Dependabot
```
[ ] Yes
[x] No
```

CIV-7193 Renovate weekly schedule and concurrency limit

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json

- [x ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/CIV-7209
Added hearing-schedule-access role to national-business-centre access profile for adding ga hearing notice document to main claim. Before this change its failing because of permissions
```
[ ] Yes
[x ] No
```

CIV-7209 Added hearing-schedule-access to national-business-centre access profile

---

charts/civil-ccd/values.template.yaml

CIV-0000 updateing charts to switch wa for civils

---

e2e/fixtures/events/informAgreeExtensionDateSpec.js

CIV-000 Change dateNoWeekends to 30 days for informed agreed extension

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldDJ.json

…worker-civil-staff" roles for  Judgment related fields
```
[ ] Yes
[ ] No
```

CIV-000 Fix Judgment tab for Staff user

---

ccd-definition/AuthorisationCaseEvent/systemUpdateDJ.json
ccd-definition/AuthorisationCaseState/AuthorisationCaseState.json

CIV-000 All staff should see the judicial referral state

---

e2e/api/steps.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/acknowledgeClaim_Solicitor1.js
e2e/fixtures/events/1v2SameSolicitorEvents/defendantResponse_sameSolicitor.js
e2e/fixtures/events/2v1Events/acknowledgeClaim_2v1.js
e2e/fixtures/events/acknowledgeClaim.js
e2e/fixtures/events/defendantResponse.js
e2e/helpers/caseFlagsFeatureHelper.js

- Ensured flag fields are removed in aat environment until release.
- Removed uneccessary flag fields in invalid test scenarios.
```
[ ] Yes
[X] No
```

CIV-0000 Fix api tests in aat env

---

e2e/config.js

https://tools.hmcts.net/jira/browse/CIV-7274
set localNocTests config to false
```
[ ] Yes
[ ] No
```

CIV-7274 NoC API config

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.template.yaml

CIV-0000 Common Data url

---

ccd-definition/CaseEvent/User/UserEventsLRspec-nonprod.json
ccd-definition/CaseEvent/User/UserEventsLRspec-prod.json
ccd-definition/CaseEvent/User/UserEventsLRspec.json

CIV-0000- Moving Claimant_response_spec event to prod file as it also exists in CUI non-prod file
```
[ ] Yes
[x ] No
```

CIV-0000 Moving Claimant_response_spec event to prod file

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldSDO-DJ.json

Addition of GS_profile to SDO DJ documents authorisation so staff can view using challenged access
```
[ ] Yes
[ x] No
```

CIV-0000 update authos for documents DJ SDO

---

e2e/api/steps_LRspec.js
e2e/api/steps_LRspecCui.js
e2e/api/steps_LRspecFast.js

CIV-0000- Changing state check to Judicial referral for all environments
```
[ ] Yes
[x ] No
```

CIV-0000 Changing state check to Judicial referral for all environments

---

ccd-definition/AuthorisationCaseField/AuthorisationFinalOrders-nonprod.json
ccd-definition/CaseEvent/User/UserEventsCaseProg-nonprod.json
ccd-definition/CaseEventToFields/FinalOrders-nonprod.json
ccd-definition/CaseField/CaseFieldFinalOrders-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/OrderOnCourtInitiative-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/OrderWithoutNotice-nonprod.json
ccd-definition/FixedLists/CaseProgression/FinalOrderSelection-nonprod.json
ccd-definition/FixedLists/CaseProgression/OrderOnCourtInitiativeList-nonprod.json

Free form order page for https://tools.hmcts.net/jira/browse/CIV-6292
```
[ ] Yes
[x ] No
```

CIV-6292 Feat/civ 6292 free form order

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventCaseProg-nonprod.json

CIV-7739 Removed judge profile and legal advisor role for hearing schedule event

---

charts/civil-ccd/Chart.yaml

upgrading the version for ccd chart
```
[ ] Yes
[x ] No
```

CIV-0000 upgrading the version for ccd chart

---

ccd-definition/FixedLists/ShowConditionFlagSpec.json

https://tools.hmcts.net/jira/browse/CIV-6215
Declaration of a value that is used in the ccd and the service PRs
```
[ ] Yes
[X] No
```

CIV-6215 preparation for 6215 other PRs

---

e2e/api/steps.js
e2e/fixtures/events/scheduleHearing.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v1_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v2_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_2v1_test.js
e2e/tests/api_tests/sdo/sdo_test.js

Hearing Notice API Tests for DJ and SDO journeys

CIV-5171 - Hearing Notice API tests

---

ccd-definition/CaseEvent/User/UserEvents-CaseFlags-nonprod.json

CIV-7784 Add  publish for case flag

---

bin/add-roles.sh

https://tools.hmcts.net/jira/browse/CIV-7850
Added error exit to the add roles script to stop silent failures impacting further down the pipeline
```
[ ] Yes
[x] No
```

CIV-7850 stop silent failures in add roles script

---

bin/create-github-release.sh

N/A
A recent change to prevent errors to be swallowed silently brought up a broken bit of code.
The code has been temporarily commented out in this PR, to allow the build to continue while we sort out what things should look like.
```
[ ] Yes
[x] No
```

CIV-TASK Fix broken AAT build

---

bin/utils/process-definition.sh

CIV-0000 reverting back to ccd processor latest as the issue is fixed

---

ccd-definition/CaseTypeTab/ApplicationsJudgeGAspec.json
ccd-definition/CaseTypeTab/ApplicationsLegalAdviserGAspec.json

CIV-8110 legaladviser applications tab permission

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json

Updates to avoid case file view showing duplicate documents in case file tab
https://tools.hmcts.net/jira/browse/CIV-8075
```
[ ] Yes
[x ] No
```

CIV-8075 fixing duplicate docs case file view

---

charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml

CIV-7105 adding new GA keyvault changes

---

Jenkinsfile_CNP

Pulling latest master branch for camunda changes in staging
```
[ ] Yes
[ ] No
```

CIV-0000 Pulling latest master branch for camunda changes in staging

---

ccd-definition/CaseEventToFields/ClaimantResponseLRspec-prod.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec.json

move pageShowCondition
move pageShowCondition to correct place
```
[ ] Yes
[X] No
```

CIV-6295 fix master

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec-CUI-nonprod.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec-CUI-nonprod.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec-nonprod.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec-prod.json
ccd-definition/CaseEventToFields/ClaimantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec-CUI-nonprod.json

Fix for the CUI side for duplicate field
```
[ ] Yes
[x] No
```

CIV-0000 Fix for CUI side for duplicate field

---

charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-5229
revert pointing civil-service PR
```
[ ] Yes
[ ] No
```

CIV-000 revert pointing preview PR

---

ccd-definition/CaseEventToFields/ClaimantResponseLRspec-prod.json

https://tools.hmcts.net/jira/browse/CIV-6295
fix PR issue
```
[ ] Yes
[X] No
```

CIV-6295 fix PR issue

---

e2e/fixtures/events/defendantResponseSpec.js

https://tools.hmcts.net/jira/browse/CIV-6421
Update defendantResponseSpec.js with caseLocation
```
[ ] Yes
[X] No
```

CIV-6241 Update defendantResponseSpec

---

bin/build-release-ccd-definition.sh

CIV-5011 shutter with jenkins AAT

---

bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-5011

CIV-5011 shutter with jenkins PROD

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#2712

CIV-5011 Un-shutter with jenkins PROD

---

e2e/pages/informAgreedExtensionDate/date.page.js
e2e/pages/noticeOfChange.page.js
e2e/tests/ui_tests/noticeofchange/1v2_lips_to_same_sols_test.js

Inform agreed extension event is not showing up event submission in a separate page, continue button has been removed. Not sure what change caused this but it is breaking pipelines and also Noc link is not appearing in menu bar @sankaviv1 is checking with ExUI on this but providing a fix in this pr as this is blocking all ccd pr's

CIV-0000 Shorter term Skip noc menu link check as the menu bar is not showing up

---

e2e/pages/noticeOfChange.page.js

- unskip noc e2e
```
[ ] Yes
[ ] No
```

CIV-0000 Unskip noc test

---

ccd-definition/CaseEventToFields/DefendantResponseLRspec-hnl-legal-rep.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/FixedLists/ShowConditionFlagSpec-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-9101
change PageShowCondition
```
[ ] Yes
[X] No
```

CIV-9101 DQ questions displaying in all Admit All defendant response journeys Spec claims

---

e2e/config.js
e2e/steps_file.js

CIV-0000 Fix for judge passwords

---

e2e/api/steps.js
e2e/api/steps_LRspecSmall.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_test.js

Adding await to removeFlagFieldsFromFixture
```
[ ] Yes
[ ] No
```

CIV-000 Fix for caseflags test

---

e2e/tests/api_tests/hearings/api_1v1_spec_small_hearings_test.js
e2e/tests/api_tests/hearings/api_1v2DS_unspec_fast_hearings_test.js
package.json

- temporarily skip hearings api test
```
[ ] Yes
[ ] No
```

CIV-0000 Skip hearings api

---

e2e/api/steps_hearings.js

https://tools.hmcts.net/jira/browse/CIV-6261
- update api test assert
```
[ ] Yes
[ ] No
```

CIV-6261 Hearing channels default

---

bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-7581
Update build-release-ccd-definition.sh for shuttering civil-ccd

CIV-7581 Shutter civil-ccd

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#2908

CIV-7581 Revert Shutter civil-ccd

---

e2e/api/steps_hearings.js

https://tools.hmcts.net/jira/browse/CIV-8999
- update asserts
```
[ ] Yes
[ ] No
```

CIV-8999 Change to SLA start date and screen flow

---

bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-7581
Update build-release-ccd-definition.sh for shuttering civil-ccd 
reverting release

CIV-7581 Shutter civil-ccd release revert

---

e2e/api/steps_hearings.js

https://tools.hmcts.net/jira/browse/CIV-9480
- change field name
```
[ ] Yes
[ ] No
```

CIV-9480 HMC payload amends

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#2913
https://tools.hmcts.net/jira/browse/CIV-7581

CIV-7581 Revert Shutter civil-ccd release revert

---

e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js

https://tools.hmcts.net/jira/browse/CIV-8582

CIV-8582 Putting test back after civil service merge

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-6241
add permissions to citizen user to see ccd fields that are required for dashboard statuses
```
[ ] Yes
[ ] No
```

CIV-6241 add permissions to fields for lip defendant

---

ccd-definition/CaseEventToFields/NotifyDefendantOfClaim-COS-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-9600
```
[ ] Yes
[ ] No
```

CIV-9600 Show warning error

---

ccd-definition/CaseField/EvidenceUpload-nonprod.json
ccd-definition/Categories/Categories-nonprod.json
ccd-definition/FixedLists/CaseProgression/EvidenceUploadExpert-nonprod.json
ccd-definition/FixedLists/CaseProgression/EvidenceUploadExpertSmallClaim-nonprod.json

…"Joint Statement of Experts / Single Joint Expert Report"
https://tools.hmcts.net/jira/browse/CIV-8140
wording change
```
[ ] Yes
[x] No
```

CIV-8140 rename on screen wording

---

ccd-definition/FixedLists/DocumentType.json

https://tools.hmcts.net/jira/browse/CIV-9807
Added new doc type for uploaded translated document for defendant response.
```
[ ] Yes
[x] No
```

CIV-9807 - Upload Translated Document requires new Document type

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json

CIV-6250 - adding auth for applicant's deadline
```
[ ] Yes
[ ] No
```

CIV-6250 - adding auth for applicant's deadline

---

e2e/api/steps_LRspec.js
e2e/api/steps_LRspecCui.js

Tested nightly pipeline here https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_a_to_c_Nightly%2Fcivil-service/detail/nightly-dev/1/pipeline/

CIV-0000 Fix nightly civil service

---

bin/add-roles.sh

CIV-0000  Add citizen profile

---

e2e/fixtures/events/claimantResponseSpec.js
e2e/fixtures/events/claimantResponseSpec1v2.js
e2e/fixtures/events/claimantResponseSpec1v2Fast.js
e2e/fixtures/events/claimantResponseSpec2v1.js
e2e/fixtures/events/claimantResponseSpec2v1Fast.js
e2e/fixtures/events/defendantResponseSpec.js
e2e/fixtures/events/defendantResponseSpec1v2.js
e2e/fixtures/events/defendantResponseSpec1v2Fast.js
e2e/fixtures/events/defendantResponseSpec2v1.js
e2e/fixtures/events/defendantResponseSpec2v1Fast.js
e2e/fixtures/events/defendantResponseSpecCui.js

CIV-8610 fix functional test

---

e2e/fixtures/events/evidenceUploadApplicant.js

https://tools.hmcts.net/jira/browse/CIV-8432
fix test data payload
```
[ ] Yes
[x] No
```

CIV-8432 fix app resp payload

---

charts/civil-ccd/values.template.yaml
codecept.conf.js
e2e/pages/caseView.page.js

- [x ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/CIV-8432
Reverted back to civil-service latest
```
[ ] Yes
[x ] No
```

CIV-8432 Removed pr-image of civil-service

---

charts/civil-ccd/values.preview.template.yaml
e2e/api/steps.js

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/CIV-9924
Change description
Update confirmation header and summary for LR vs Lip spec and unspec cases when PBAV3 is on.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ ] No

CIV-9924 commenting Body and header change for test

---

charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-9924

CIV-9924  reverting pointing to PR

---

.github/workflows/main.yml

upping the number length from 4 to 5 for CIV ticket numbers
```
[ ] Yes
[x] No
```

CIV-00000 Changing naming pattern for prs

---

ccd-definition/CaseEvent/User/UserEventsCaseProg-nonprod.json

Retriggering hearing listing event, now being published
```
[ ] Yes
[ x] No
```

CIV-0000 publish relisting event

---

e2e/api/steps_LRspec.js
e2e/api/steps_LRspecCui.js
e2e/api/steps_LRspecFast.js
e2e/api/steps_LRspecSmall.js
e2e/fixtures/events/informAgreeExtensionDateSpec.js

https://tools.hmcts.net/jira/browse/CIV-9230
Undo spec changes. Ticket is to be applied only for Damages
```
[ ] Yes
[X] No
```

CIV-9230 ticket was only for Damages, not LR

---

e2e/tests/api_tests/lrspec/api_spec_bulk_test.js
e2e/tests/api_tests/sdo/sdo_test.js

reenable api test for final order
```
[ ] Yes
[x ] No
```

CIV-0000 reenable disabled tests for final order

---

e2e/api/steps.js

https://tools.hmcts.net/jira/browse/CIV-9399
- Fixed failing api test
```
[ ] Yes
[X] No
```

CIV-9399 Api Test Fix

---

e2e/api/steps_LRspec.js
e2e/api/steps_LRspecFast.js

https://tools.hmcts.net/jira/browse/CIV-9355
if applicant does not proceed, state should not become judicial referral
```
[ ] Yes
[X] No
```

CIV-9355 not proceed should not be judicial referral

---

e2e/tests/api_tests/sdo/sdo_test.js

Reenabling assisted order tests for final order
```
[ ] Yes
[ x] No
```

CIV-10066 renable assisted order tests

---

Jenkinsfile_CNP
charts/civil-ccd/values.aat.template.yaml

https://tools.hmcts.net/jira/browse/CIV-10456
- use internal aac url
```
[ ] Yes
[ ] No
```

CIV-10456 Point to right aac url for aat

---

.github/renovate.json

CIV-10461
Update renovate configs
```
[ ] Yes
[x] No
```

CIV-10461 Update renovate configs

---

e2e/tests/api_tests/sdo/sdo_test.js

https://tools.hmcts.net/jira/browse/CIV-10067
reenable test
```
[ ] Yes
[ x] No
```

CIV-0000 Update sdo_test.js to reenable final tests

---

e2e/api/steps_LRspec.js

CIV-000 fix camunda smoke test

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldCaseProg-nonprod.json
ccd-definition/AuthorisationCaseField/BundlesCaseField-nonprod.json
ccd-definition/AuthorisationCaseField/EvidenceUpload-nonprod.json

updated permissions for judges and evidence upload
https://tools.hmcts.net/jira/browse/CIV-10550
https://tools.hmcts.net/jira/browse/CIV-9805
```
[ ] Yes
[ x] No
```

CIV-10550 permission update

---

Jenkinsfile_CNP

CIV-0000 fix checkForEnableHelmLabel

---

bin/build-release-ccd-definition.sh
ccd-definition/CaseEventToFields/CreateClaimLRspec.json

CIV-000 Shutter config for CoS NoC

---

charts/civil-ccd/values.template.yaml

CIV-000 Whitelist aac with ccd pod for staging

---

e2e/tests/api_tests/damages/api_noc_unspec_test.js
e2e/tests/api_tests/lrspec/api_noc_spec_test.js

CIV-000 disable noc api temporarily

---

e2e/tests/api_tests/damages/api_noc_unspec_test.js
e2e/tests/api_tests/lrspec/api_noc_spec_test.js

Reverts hmcts/civil-ccd-definition#3255

CIV-0000 - Reinstate NoC API Tests

---

ccd-definition/ComplexTypes/ClaimantMediationLip-CUI-R2-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-10601
```
[ ] Yes
[x] No
```

CIV-10601 Fieldshowconditions added

---

ccd-definition/ComplexTypes/CaseProgression/AssistedOrderAppeal/AppealChoiceDropdownTwoARefuse-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/AssistedOrderAppeal/AppealChoiceDropdownTwoBRefuse-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/AssistedOrderAppeal/AppealChoiceFirstDropdownRefuse-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/AssistedOrderAppeal/AppealsFinalOrders-nonprod.json
ccd-definition/ComplexTypes/CaseProgression/AssistedOrderJudgeheardFrom/CaseTrialNotice-nonprod.json
e2e/fixtures/events/finalOrder.js
e2e/tests/api_tests/sdo/sdo_test.js

https://tools.hmcts.net/jira/browse/CIV-9763
Appeal changes
```
[ ] Yes
[x ] No
```

CIV-9763 assisted orders document update

---

ccd-definition/ComplexTypes/GAHearingDateGAspec.json
ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json

https://tools.hmcts.net/jira/browse/CIV-10231
1. Update any reference to Settle or Discontinue by consent to Settle by consent including the error messages
2. On the Is there a hearing screen, update the question asked to be: Is the application for an adjournment of a hearing which is at least 14 days away?
and if yes date field reads: Please provide the hearing dates
Help text to be updated to: If there is is more than one hearing, please provide the date of the earliest hearing
```
[ ] Yes
[ ] No
```

CIV-10231 Update Application Type Name

---

e2e/tests/api_tests/sdo/sdo_test.js

renable disabled final order tests
```
[ ] Yes
[x ] No
```

CIV-0000 Update sdo_test.js

---

bin/build-release-ccd-definition.sh

Unshuttered 
```
[ ] Yes
[X] No
```

CIV-10834 Added unshutter config

---

ccd-definition/AuthorisationCaseField/AuthorisationFinalOrders-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-10872
update perms for final order document, so staff and solicitors can view
```
[ ] Yes
[x ] No
```

CIV-10872 update final order doc permissions

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventCaseProg-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-10930
update perms so each respondent/applicant solictor can see submission of event
```
[ ] Yes
[x ] No
```

CIV-10930 update perms evidence upload

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec.json
ccd-definition/CaseEventToComplexTypes/DefendantResponseLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json
e2e/fixtures/events/defendantResponseSpec.js
e2e/fixtures/events/defendantResponseSpec1v2.js
e2e/fixtures/events/defendantResponseSpec1v2Fast.js
e2e/fixtures/events/defendantResponseSpec2v1.js
e2e/fixtures/events/defendantResponseSpec2v1Fast.js
e2e/fixtures/events/defendantResponseSpecCui.js
e2e/fixtures/events/defendantResponseSpecSmall.js
e2e/fragments/confirmDefendantsDetailsLRspec.js
e2e/fragments/confirmLegalRepDetailsLRspec.js
e2e/pages/respondToClaimLRspec/enter2ndDefendantDetailsLRspec.page.js

Reverting changes for to fix master specAoSApplicantCorrespondenceAddressdetails is being updated when defendant updates address

CIV-8923 changes for to fix master

---

ccd-definition/ComplexTypes/DQ/RemoteHearing.json

https://tools.hmcts.net/jira/browse/CIV-3955

CIV-0000 RemoteHearing reason should be visible only of we say Yes

---

Jenkinsfile_CNP
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml
e2e/config.js

…ds (#3355)"
This reverts commit a1d186c8edc24b20e644fb4b4490a51e139ca1ab.
https://tools.hmcts.net/jira/browse/CIV-10624
revert changes
```
[ ] Yes
[X] No
```

CIV-10624 - Revert changes

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#3285

CIV-7581 Revert Shuttering config

---

e2e/tests/ui_tests/damages/1v2CreateClaim_DiffSol_test.js
e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_test.js

Reverts hmcts/civil-ccd-definition#3372

CIV-0000 remoteHearingRequested_radio radio is not present Revert 

---

bin/build-release-ccd-definition.sh

CIV-0000 Shutter for case flags release

---

e2e/api/steps.js
e2e/fixtures/events/claimantResponseSpec2v1Fast.js
e2e/fixtures/events/claimantResponseSpecSmall.js
e2e/tests/api_tests/damages/api_1v1_test.js
e2e/tests/api_tests/damages/api_1v2_different_solicitor_test.js
e2e/tests/api_tests/damages/api_1v2_same_solicitor_test.js
e2e/tests/api_tests/damages/api_2v1_test.js

- remove unnecessary fixture data
```
[ ] Yes
[ ] No
```

CIV-000 Fix fixture data for spec claimant response api

---

e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js

- Use region 4 user for unspec dj api
```
[ ] Yes
[ ] No
```

CIV-0000 Fix unspec dj e2e

---

charts/civil-ccd/values.template.yaml

https://tools.hmcts.net/jira/browse/CIV-10624
Fix
```
[ ] Yes
[X] No
```

CIV-10624 remove secrets form values.yaml

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/CIV-10624
Update file Jenkinsfile_nightly with 3 new KV Secrets:
1. default-password
2. judge-default-password
3. iac-default-password
```
[ ] Yes
[X] No
```

CIV-10624 update Jenkinsfile_nightly secrets

---

bin/build-release-ccd-definition.sh

Reverts hmcts/civil-ccd-definition#3490

CIV-7581 Revert "Shuttering for CIV-7581"

---

ccd-definition/CaseField/CaseField-CUI-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-CUI-nonprod.json
ccd-definition/ComplexTypes/UserDetails.json

Making CUI fields searchable
```
[ ] Yes
[ ] No
```

CIV-0000 Making CUI fields searchable

---

ccd-definition/CaseField/CaseFieldFinalOrders-nonprod.json
ccd-definition/FixedLists/CaseProgression/FinalOrdersCostSelection-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-11418
and
https://tools.hmcts.net/jira/browse/CIV-11352
updated labels on final order page, for cost list, and reasons section 
```
[ ] Yes
[x] No
```

CIV-11418 including civ-11352 label changes

---

e2e/tests/api_tests/lrspec/api_2v1_spec_test.js

- change admin user for case flags 2v1 spec
```
[ ] Yes
[ ] No
```

CIV-0000 Use region 2 admin for 2v1 spec case flags

---

ccd-definition/CaseEventToFields/FeatureToggle-WAToggle-nonprod.json
ccd-definition/CaseEventToFields/FeatureToggle-WAToggle.json

https://tools.hmcts.net/jira/browse/CIV-10922
TOC-NotsuitableSDO- Remove WA flag from screen
```
[ ] Yes
[ X] No
```

CIV-10922 TOC-NotsuitableSDO- Remove WA Feature Toggle flag from screen

---

ccd-definition/CaseEventToFields/FeatureToggle-WAToggle-nonprod.json
ccd-definition/CaseEventToFields/FeatureToggle-WAToggle.json

Reverts hmcts/civil-ccd-definition#3517

CIV-10922 Revert CIV-10922 TOC-NotsuitableSDO- Remove WA Feature Toggle flag from screen

---

ccd-definition/CaseEventToFields/FeatureToggle-WAToggle-nonprod.json
ccd-definition/CaseEventToFields/FeatureToggle-WAToggle.json

https://tools.hmcts.net/jira/browse/CIV-10922
removing Feature Toggle flag from TOC screen
```
[ ] Yes
[ X] No
```

CIV-10922 toc reconfigure tasks

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec.json
ccd-definition/CaseEventToComplexTypes/DefendantResponseLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json
e2e/fixtures/events/defendantResponseSpec.js
e2e/fixtures/events/defendantResponseSpec1v2.js
e2e/fixtures/events/defendantResponseSpec1v2Fast.js
e2e/fixtures/events/defendantResponseSpec2v1.js
e2e/fixtures/events/defendantResponseSpec2v1Fast.js
e2e/fixtures/events/defendantResponseSpecCui.js
e2e/fixtures/events/defendantResponseSpecSmall.js
e2e/fragments/confirmDefendantsDetailsLRspec.js
e2e/pages/respondToClaimLRspec/enter2ndDefendantDetailsLRspec.page.js

https://tools.hmcts.net/jira/browse/CIV-8923
specAoSApplicantCorrespondenceAddressdetails is being updated when defendant updates address
```
[ ] Yes
[x] No
```

CIV-8923 specAoSApplicantCorrespondenceAddressdetails is being updated when defendant updates address

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec.json
ccd-definition/CaseEventToComplexTypes/DefendantResponseLRspec.json
ccd-definition/CaseEventToFields/DefendantResponseLRspec.json
ccd-definition/CaseField/CaseFieldLRspec.json
e2e/fixtures/events/defendantResponseSpec.js
e2e/fixtures/events/defendantResponseSpec1v2.js
e2e/fixtures/events/defendantResponseSpec1v2Fast.js
e2e/fixtures/events/defendantResponseSpec2v1.js
e2e/fixtures/events/defendantResponseSpec2v1Fast.js
e2e/fixtures/events/defendantResponseSpecCui.js
e2e/fixtures/events/defendantResponseSpecSmall.js
e2e/fragments/confirmDefendantsDetailsLRspec.js
e2e/fragments/confirmLegalRepDetailsLRspec.js
e2e/pages/respondToClaimLRspec/enter2ndDefendantDetailsLRspec.page.js

CIV-8923
revert changes from 8923
```
[ ] Yes
[X] No
```

CIV-8923 revert

---

ccd-definition/CaseEventToFields/DefaultJudgmentDJ.json
ccd-definition/ComplexTypes/CaseLocation.json
e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js

fix for caseManagementLocation not being saved/retained, when changed in DefaultJudgment event
```
[ ] Yes
[ x] No
```

CIV-0000 caseManagementLocation DJ retaining

---

e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js

Fix updated test to correct user
```
[ ] Yes
[ x] No
```

CIV-0000 fix test user type 

---

bin/build-release-ccd-definition.sh

CIV-0000 unShutter prod release

---

Jenkinsfile_CNP
e2e/config.js
e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js
wa/tasks/scheduleAHearing.js
wa/tasks/summaryJudgmentDirectionsTask.js

Tested api changes in https://github.com/hmcts/civil-service/pull/3586

CIV-0000 Enable EA court testing for dj

---

e2e/fixtures/events/1v2DifferentSolicitorEvents/acknowledgeClaim_Solicitor1.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/acknowledgeClaim_Solicitor2.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/defendantResponse_Solicitor1.js
e2e/fixtures/events/1v2SameSolicitorEvents/acknowledgeClaim_sameSolicitor.js
e2e/fixtures/events/1v2SameSolicitorEvents/defendantResponse_sameSolicitor.js
e2e/fixtures/events/2v1Events/acknowledgeClaim_2v1.js
e2e/fixtures/events/2v1Events/defendantResponse_2v1.js
e2e/fixtures/events/acknowledgeClaim.js
e2e/fixtures/events/defendantResponse.js
e2e/helpers/assertions/caseFlagsAssertions.js
e2e/tests/ui_tests/damages/1v1CreateClaim_test.js
e2e/tests/ui_tests/damages/1v2CreateClaim_DiffSol_test.js
e2e/tests/ui_tests/lrspec/1v1CreateClaim-LRspec_test.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_test.js

Reverts hmcts/civil-ccd-definition#3279

Revert "CIV-10382 Case flags updates for new experts/witnesses"

---

ccd-definition/CaseEvent/User/UserEventsCUI-nonprod.json

NA
Updated event enabling condition for Upload Translated Document event
```
[ ] Yes
[x] No
```

CIV-0000 - CUI WA required changes

---

ccd-definition/CaseField/EvidenceUpload.json

https://tools.hmcts.net/jira/browse/CIV-11532
the uploaded document details should be visible next to the sub section labelled 'Defendant uploaded documents' 
And within a table labelled 'Defendant uploaded documents' 
```
[ ] Yes
[ ] No
```

CIV-11532 Update Label for defendant upload doc

---

e2e/api/steps.js
e2e/api/testingSupport.js

https://tools.hmcts.net/jira/browse/CIV-10810
- remove noc/cos toggle from functional tests
```
[ ] Yes
[ ] No
```

CIV-10810 NoC/CoS cleanup

---

ccd-definition/CaseEvent/Camunda/RetriggerCase.json
charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-11363
Change "publish" to "Publish"
```
[ ] Yes
[X] No
```

CIV-11363 Update RetriggerCase.json

---

ccd-definition/CaseField/EvidenceUpload.json
ccd-definition/ComplexTypes/CaseProgression/UploadEvidenceWitness2.json
e2e/fixtures/events/evidenceUploadApplicant.js
e2e/fixtures/events/evidenceUploadRespondent.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v1_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v2_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_2v1_test.js
e2e/tests/api_tests/sdo/sdo_test.js

https://tools.hmcts.net/jira/browse/CIV-11144
add witness summary date
```
[ ] Yes
[ x] No
```

CIV-11144 add witness summary date

---

e2e/tests/api_tests/defaultJudgments/api_dj_1v1_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_1v2_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_2v1_test.js
e2e/tests/api_tests/sdo/sdo_test.js

https://tools.hmcts.net/jira/browse/CIV-11144
unskip tests after merge of civil PR
```
[ ] Yes
[ x] No
```

CIV-11144 unskip evidence upload tests

---

bin/build-release-ccd-definition.sh

CIV-0000 Activate Shuttering for CUI

---

bin/build-release-ccd-definition.sh
package.json

CIV-0000 Unshutter  CCD

---

package.json

CIV-0000 enable tests

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml

Removing
- default-password
- judge-default-password
- iac-default-password

CIV-0000 removing secrets from values

---

e2e/pages/createClaim/addClaimForAFlightDelay.page.js
e2e/pages/createClaim/addConfirmationSubmitPageValidation.page.js
e2e/steps_file_LRspec.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_FlightDelay_test.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_test.js

CIV-11494 Adding UI tests

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI-nonprod.json
ccd-definition/CaseEvent/Camunda/NotificationEvents-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-8791
```
[ ] Yes
[x] No
```

CIV-8791 Notification event

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-TOC-nonprod.json
charts/civil-ccd/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CIV-11865
Add permission to staff-admin to view NSDO reason
CCD changes to add permission to View
```
[ ] Yes
[X ] No
```

CIV-11865 Add permission to staff-admin to view NSDO reason

---

charts/civil-ccd/Chart.yaml

N/A
- downgrade the service chart version to fix master 
```
[ ] Yes
[x] No
```

CIV-00000 fix/downgrade civil-service chart version

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json
ccd-definition/CaseField/CaseField-CUI-R2-nonprod.json

Reverts hmcts/civil-ccd-definition#3549

CIV-8903 dashboard settlement agreement-revert

---

ccd-definition/CaseField/EvidenceUpload.json

[CIV-11641]https://tools.hmcts.net/jira/browse/CIV-11641
Changed type from documentType to documentTypeWithName for all DocumentRefferredToInStatement fields
```
[ ] Yes
[ ] No
```

CIV-00000 CUI team 2 releases post Christmas 

---

ccd-definition/AuthorisationCaseField/HearingNotice.json

https://tools.hmcts.net/jira/browse/CIV-7343
Give claimant access to hearing notice, so notice can be used in condition.
```
[ ] Yes
[x] No
```

CIV-7343 - give claimant access to hearing notice

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-R2-nonprod.json
ccd-definition/CaseEventToFields/NotSuitableSDO-SDO-R2-nonprod.json
ccd-definition/CaseEventToFields/NotSuitableSDO-TOC-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-11839
```
[ ] Yes
[ ] No
```

CIV-11839 Fixed permission issue for notsuitableSDO

---

e2e/api/steps.js
e2e/api/steps_LRspecSmall.js
e2e/fixtures/events/createSDO.js
e2e/tests/api_tests/sdo/sdo_test.js

https://tools.hmcts.net/jira/browse/CIV-11824
Tested civil service here https://github.com/hmcts/civil-service/pull/3839

CIV-11824 Fix WA test changed as per  civ 11084

---

ccd-definition/FixedLists/FastTrack-SDO-SDO-R2-nonprod.json
ccd-definition/FixedLists/SmallTrack-SDO-SDO-R2-nonprod.json
e2e/fixtures/events/createClaim.js
e2e/fixtures/events/defendantResponse.js
e2e/tests/api_tests/sdo_R2/api_noise_induced_hearing_loss_test.js

CIV-8327 judge fast track nihl option

---

ccd-definition/CaseEventToFields/DecisionOnReconsiderationRequest-SDO-R2-nonprod.json
ccd-definition/CaseEventToFields/FeatureToggle-WAToggle-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-11750
Publish fields for WA
```
[ ] Yes
[ X] No
```

CIV-11750 Request for reconsideratiion publish fields

---

ccd-definition/ComplexTypes/Party.json

https://tools.hmcts.net/jira/browse/CIV-12161
Update for retain email value when it is hidden
```
[ ] Yes
[x] No
```

CIV-12161 Mediation emails are not sending

---

bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-11979

CIV-0000 unshutter-prod

---

ccd-definition/CaseTypeTab/Documents-CUI-R2-nonprod.json
ccd-definition/CaseTypeTab/Documents.json

CIV-00000 Fix High level data setup issue

---

e2e/fixtures/events/1v2DifferentSolicitorEvents/defendantResponse_Solicitor1.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/defendantResponse_Solicitor2.js
e2e/fixtures/events/1v2SameSolicitorEvents/defendantResponse_sameSolicitor.js
e2e/fixtures/events/2v1Events/defendantResponse_2v1.js
e2e/fixtures/events/defendantResponse.js

Reverts hmcts/civil-ccd-definition#3903

Revert "CIV-0000 Fixed missing defendant party ids in api tests"

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-SDO-R2-nonprod.json
ccd-definition/CaseEvent/Camunda/NotificationEvents-SDO-R2-nonprod.json

* CIV-8337 Request for reconsideration initial commit
* CIV-8337 Add API tests
* CIV-8337 fix API tests
* CIV-8337 add changes to run sdoR2 test
* CIV-8337 update name
* CIV-8337 rename folder
* Update codecept.conf.js
* Update api_request_for_reconsideration_test.js
* CIV-8337 update API test to small claim
* CIV-8337 remove unused code
* CIV-8337 fix checkstyle
* CIV-11241 publish fields
* CIV-11241 fix permission
* CIV-8336 temp
* CIV-8336 temp
* CIV-8336 Judge decision on reconsideration request changes
CIV-8336 Judge decision on reconsideration request changes
* CIV-8336 Add API Tests
* CIV-8336 update API Tests
* CIV-8336 fix checkstyle
* CIV-8336 change event name
* CIV-10909 Camunda events added
* CIV-8336 update text
* CIV-8336 update text
* CIV-8336 update text
* CIV-8336 update …

CIV-0000 sprint branch

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI-nonprod.json
ccd-definition/CaseEvent/Camunda/NotificationEvents-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-12265
Email Notification to Claimant LiP in Bilingual Claim Issue
```
[ ] Yes
[x] No
```

CIV-12265 Email Notification to Claimant LiP in Bilingual Claim Issue

---

ccd-definition/CaseEventToFields/CreateSDO-SDO.json

SNI-5142
Make hearing method toggle mandatory
```
[ ] Yes
[X] No
```

CIV-5142 mandatory

---

charts/civil-ccd/values.enableWA.preview.template.yaml
charts/civil-ccd/values.preview.template.yaml

CIV-0000 Make it WA compatible
```
[ ] Yes
[ ] No
```

CIV-0000 Make it WA compatible

---

ccd-definition/CaseField/CaseFieldHearingNotice.json

NA
reverted changes added by mistake in prod
```
[ ] Yes
[x] No
```

CIV-0000 - Update CaseFieldHearingNotice.json

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-HWF-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-12567
Fix citizen permissions for HWF statuses
```
[ ] Yes
[x] No
```

CIV-12567 Fix citizen permissions for HWF statuses

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec-CUI.json

Reverts hmcts/civil-ccd-definition#4114

Revert "CIV-12847 - added authorisation."

---

ccd-definition/AuthorisationCaseEvent/systemUpdate-R2-CUI-nonprod.json
ccd-definition/CaseEvent/Camunda/DashboardEvents-R2-CUI-nonprod.json

CIV-12742 - added CCJ req notification event.

---

ccd-definition/AuthorisationCaseEvent/systemUpdate-R2-CUI-nonprod.json
ccd-definition/CaseEvent/Camunda/DashboardEvents-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-12758
Dashboard notification - Claim settled (Defendant)
```
[ ] Yes
[ ] No
```

CIV-12758 Dashboard notification - Claim settled (Defendant)

---

.github/workflows/main.yml

DTSCCI-0000 Update PR name validation

---

Jenkinsfile_nightly
package.json

Nightly dev

---

charts/civil-ccd/values.template.yaml
e2e/fixtures/events/claimantResponseSpec2v1.js

Carm should be disabled by default

CIV-0000 Update claimantResponseSpec2v1.js to fix civil service nightly

---

e2e/pages/evidenceUpload/uploadDocument.js
e2e/pages/evidenceUpload/uploadDocumentSpec.js

DTSCCI-122 - Updating tests to account for EXUI document upload rate limiting

---

charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.template.yaml

Fix  camunda configuration
```
[ ] Yes
[ ] No
```

CIV-0000 updated camunda config

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec-R2-CUI-nonprod.json

CIV-0000 duplicates fix

---

ccd-definition/CaseField/CaseField-CUI-R2-nonprod.json
ccd-definition/CaseField/CaseField-CUI-R2-prod.json
ccd-definition/CaseField/CaseField.json

To fix master build with Dashboard changes
```
[ ] Yes
[x] No
```

CIV-0000 - split respondent1ResponseDeadline into nonprod + prod

---

ccd-definition/CaseField/CaseField.json
ccd-definition/ComplexTypes/BusinessProcess.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec.json

https://tools.hmcts.net/jira/browse/DTSCCI-17
```
[ ] Yes
[ ] No
```

DTSCCI-017 readyOn searchable in ES

---

package.json

… to be added
https://tools.hmcts.net/jira/browse/DTSCCI-266
```
[ ] Yes
[ ] No
```

DTSCCI-266 adding a no ft test to serve as template

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldSDO-DJ.json

DTSCCI-282
fix bad data
```
[ ] Yes
[ ] No
```

DTSCCI-282 fix bad data

---

ccd-definition/CaseEvent/User/UserEvents-EA.json

https://tools.hmcts.net/jira/browse/CIV-13495
```
[ ] Yes
[ ] No
```

CIV-13495 - Revert Case proceeds offline state change

---

ccd-definition/CaseEventToFields/DefendantResponse.json

https://tools.hmcts.net/jira/browse/CIV-13219
Original pr: https://github.com/hmcts/civil-ccd-definition/commit/a3033d870394596cbd79d04affb238438dcdfae2#diff-17dca95bfee274f11caad0492006def597f948384289edf51aaf920441118d9bR957
Reverting mistake for page show condition
```
[ ] Yes
[ ] No
```

CIV-13219 Fixed page show condition

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventCaseProg-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseEvent/systemUpdate-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec-R2-CUI-nonprod.json
ccd-definition/CaseEvent/User/UserEvents-R2-CUI-nonprod.json
ccd-definition/CaseField/CaseField-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-13698
```
[ ] Yes
[ x ] No
```

CIV-13698 SDO Legal Adviser

---

e2e/api/steps_LRspec.js

CIV-13698 Delete requestForReconsiderationDeadline

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json
ccd-definition/CaseField/CaseFieldGAspec-R2-CUI-nonprod.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-14083
Add ask for costs field
```
[ ] Yes
[x] No
```

CIV-14083 Add ask for costs field

---

bin/build-release-ccd-definition.sh

https://tools.hmcts.net/jira/browse/CIV-13835
Unshutter prod
```
[ ] Yes
[X ] No
```

CIV-0000 Unshutter prod

---

e2e/tests/api_tests/sdo_R2/api_dispute_resolution_hearing_test.js
e2e/tests/api_tests/sdo_R2/sdo_flight_delay_test.js

FIx Prod API tests
Flight delay and DRH

CIV-000 fix API tests

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-CUI-CP-nonprod.json
ccd-definition/CaseField/CaseField-CUI-CP-nonprod.json
ccd-definition/FixedLists/DocumentType-CUI-CP-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-13930
Request for reconsideration LiP Document
```
[ ] Yes
[x] No
```

CIV-13930 - request for reconsideration lip document

---

e2e/pages/manageContactInformation/manageOrganisationIndividuals.page.js
e2e/tests/ui_tests/default_judgement/1v1UnspecDJ_test.js

DTSCCI-358
Tests will be fixed as part of this ticket

DTSCCI-358 - Casemangement location is not correctly updated for DJ cases. So skipping tests

---

ccd-definition/CaseEventToFields/CreateSDO-SDO.json

https://tools.hmcts.net/jira/browse/CIV-14220
https://tools.hmcts.net/jira/browse/CIV-14202
https://tools.hmcts.net/jira/browse/CIV-14203
Fast Track SDO trial document fixes
```
[ ] Yes
[X ] No
```

CIV-14220 Fast Track SDO changes

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.template.yaml

DTSCCI-490
remove deprecated property volume lib
```
[ ] Yes
[ ] No
```

DTSCCI-490 remove deprecated property volume lib

---

sonar-project.properties

CIV-0000 Update sonar-project.properties

---

ccd-definition/CaseEventToComplexTypes/CreateSDO-SDO.json
ccd-definition/CaseEventToFields/CreateSDO-SDO.json

https://tools.hmcts.net/jira/browse/CIV-13825
Update cml when sdo and legal advisor spec under 1000 ccmcc
```
[ ] Yes
[x ] No
```

CIV-13825 cml sdo legal advisor

---

ccd-definition/CaseField/CaseField-R2-CUI-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-prod.json
ccd-definition/CaseField/CaseFieldLRspec.json

CIV-13747 JudgmentByAdmission-Dashboard-notifications-are-not-correct

---

ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-CUI-R2-nonprod.json
ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-CUI.json

CIV-0000 FIx pcq role

---

charts/civil-ccd/Chart.yaml

DTSCCI-567 
update service bus chart
```
[ ] Yes
[ ] No
```

DTSCCI-567 update service bus chart

---

ccd-definition/CaseField/CaseField-CUI-R2-nonprod.json

CIV-00000 Make pcqId searchable

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json

CIV-00000 ADD caseworker-civil code for pcqid

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json

CIV-0000 ADD caseworker-civil code for pcqid

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json

CIV-0000 ADD caseworker-civil-staff role for pcqid

---

charts/civil-ccd/Chart.yaml

DTSCCI-567 
rollback service bus chart
```
[ ] Yes
[ ] No
```

DTSCCI-567 rollback service bus chart

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json

CIV-0000 Remove extra roles for pcqid

---

charts/civil-ccd/values.template.yaml

CIV-0000 pointing to latest XUI image

---

ccd-definition/CaseEvent/User/UserEventsCUI.json

Reverts hmcts/civil-ccd-definition#4683

Revert "CIV-14707 Manage documents states"

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI-nonprod.json
ccd-definition/CaseEvent/Camunda/NotificationEvents-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-14881
I added changes to send the SDO order to the LiP Claimant.
```
[ ] Yes
[x] No
```

CIV-14881 - Send SDO order to LiP Claimant. 

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-caseworkerEvents-nonprod.json
ccd-definition/CaseEvent/User/UserEvents-caseworkerEvents-nonprod.json

PR for https://tools.hmcts.net/jira/browse/CIV-14824

CIV-14824 Dismiss Case Permissions

---

ccd-definition/CaseEventToFields/WorkAllocationIntegrationFields-CUI-R2-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15022
```
[ ] Yes
[ ] No
```

CIV-15022 - SDO task not being created for LA when claim was in mediation

---

package.json

DTSCCI-000 - Changing api-nightly-prod report name

---

README.md
bin/setup-devuser-preview-env.sh

DTSCCI-763 amending script for different dependency branches

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-JO-nonprod.json
ccd-definition/CaseEvent/Camunda/CaseEvents-JO-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-14869
- Added two new events: SEND_JUDGMENT_DETAILS_CJES_SA, SEND_JUDGMENT_DETAILS_CJES
```
[ ] Yes
[ ] No
```

CIV-14869 CJES Service : RECORD_JUDGMENT

---

e2e/tests/api_tests/lrspec/api_1v1_spec_test.js
e2e/tests/api_tests/lrspec/api_1v2_spec_test.js

DTSCCI-000 - making settle claim test 1v2 run only in nonprod

---

e2e/tests/api_tests/sdo_R2/api_request_for_reconsideration_test.js

DTSCCI-849 - Changing judges used in req for reconsideration test to region 1

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-CUI-CP-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15044
Add authorisation to allow defendant access to their document for disclosure
```
[ ] Yes
[x] No
```

CIV-15044 - Add authorisation for document for disclosure defendant

---

ccd-definition/CaseEvent/User/UserEvents-SettleDiscontinue-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15208
SETTLE_CLAIM_MARK_PAID_FULL event's name and desc updated to "Mark claim as paid in full"
```
[ ] Yes
[ ] No
```

CIV-15208 Rename Settle the claim to Mark claim as paid in full

---

README.md
bin/setup-devuser-preview-env.sh

DTSCCI-694 amending script for dev env

---

bin/variables/load-dev-user-preview-environment-variables.sh

…v script
```
[ ] Yes
[ ] No
```

DTSCCI-000 fixing the env var for civil-service in the dev preview

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-JO-CUI-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-R2-CUI-nonprod.json

Move activeJudgment CUI auth to JO file
```
[ ] Yes
[x] No
```

CIV-0000 Move activeJudgment CUI auth to JO file

---

e2e/api/steps.js

CIV-0000 Fix Api Tests

---

e2e/tests/api_tests/defaultJudgments/api_dj_spec_1v1_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_spec_1v2_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_spec_2v1_test.js

DTSCCI-927
disable dj spec api tests
```
[ ] Yes
[ ] No
```

DTSCCI-927 disable dj spec api tests

---

build.gradle

DTSCCI-927
disable dj spec api tests
```
[ ] Yes
[ ] No
```

DTSCCI-000 remove jcenter reference

---

bin/build-release-ccd-definition.sh

CIV-0000 - Unshutter Prod

---

Jenkinsfile_CNP
e2e/tests/api_tests/hearings/api_1v2DS_unspec_fast_hearings_test.js
e2e/tests/api_tests/hearings/api_1v2_spec_fast_hearings_test.js
e2e/tests/ui_tests/damages/1v2CreateClaim_DiffSol_fast_track_test.js
e2e/tests/ui_tests/damages/1v2CreateClaim_DiffSol_small_claims_test.js
e2e/tests/ui_tests/lrspec/1v2CreateClaim-LRspec_DiffSol_test.js
e2e/tests/ui_tests/sdo/ui_request_for_reconsideration_test.js
e2e/tests/ui_tests/settle_discontinue/1v2SettleThisClaim_test.js

CIV-0000 change ea courts to false

---

ccd-definition/AuthorisationCaseEvent/systemupdate-CUI-CP-nonprod.json
ccd-definition/CaseEvent/Camunda/DashboardEvents-CUI-CP-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-14191
Auto hearing notice dashboard notification task added
```
[ ] Yes
[x] No
```

CIV-14191 - add auto hearing notice dashboard notification

---

e2e/config.js

…ef Data change
```
[ ] Yes
[ ] No
```

DTSCCI-000 - Updating Nottingham Court spelling so that it reflects Ref Data change

---

e2e/tests/ui_tests/hearings/1v2_Diff_Sols_Create_fast_track_With_Hearing_Request_test.js

CIV-00000 Run hearing test on nightly only

---

ccd-definition/ComplexTypes/Party.json

https://tools.hmcts.net/jira/browse/CIV-15569
Change email check to >320 chars
```
[ ] Yes
[x] No
```

CIV-15569 Change email check to >320 chars

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-CARM-nonprod.json
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI.json

https://tools.hmcts.net/jira/browse/CIV-15513
Fixed the permission issues.
```
[ ] Yes
[x] No
```

CIV-15513 - Claim history tab displaying incorrect state change

---

ccd-definition/AuthorisationCaseEvent/systemUpdate-caseworkerEvents-nonprod.json
ccd-definition/CaseEvent/Camunda/NotificationEvents-caseworkerEvents-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15230
```
[ ] Yes
[ x ] No
```

CIV-15230 LR notification stay update requested

---

ccd-definition/CaseEvent/User/UserEvents-amendBundle-nonprod.json
ccd-definition/CaseEvent/User/UserEvents-amendBundle-prod.json

(https://tools.hmcts.net/jira/browse/CIV-15523)
Make "Manage documents" available to UNSPEC 
```
[ ] Yes
[x] No
```

CIV-15523 sdd for unespec claims

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-CUI-CP-nonprod.json
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-HWF-R2-CUI.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-CUI-CP-nonprod.json

CIV-15152
service changes require systemupdate to read HWF events
```
[ ] Yes
[X] No
```

CIV-15152 allow read to system update so these events are readable

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI.json
ccd-definition/AuthorisationCaseState/AuthorisationCaseState-CUI.json

https://tools.hmcts.net/jira/browse/CIV-15678
Updated permissions for LIP_CLAIM_SETTLED ecent
```
[ ] Yes
[x] No
```

CIV-15678 -  CUI-Admin role cannot see 'case settled' event on event history tab

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-CUI-CP-nonprod.json

PR for https://tools.hmcts.net/jira/browse/CIV-15281

CIV-15281 DecisionOnRequestReconsiderationOptions Permissions

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-R2-CUI.json
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventCUI-DTSCCI-927-nonprod.json
ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventDJspec.json
ccd-definition/CaseEvent/User/UserEventsSpecDJspec-prod.json

…ui-r2
DTSCCI-1134 
enable default judgement and judgement by admission
```
[ ] Yes
[ ] No
```

DTSCCI-1134 enable default judgement and judgement by admission

---

e2e/tests/api_tests/lrspec_cui/api_1v1_spec_cui_discontinue_claim_test.js
e2e/tests/api_tests/settle-discontinue/api_settle_discontinue_claim_2v1_spec_test.js
e2e/tests/ui_tests/settle_discontinue/1v1DiscontinueThisClaim_test.js
e2e/tests/ui_tests/settle_discontinue/1v2DiscontinueThisClaim_test.js
e2e/tests/ui_tests/settle_discontinue/2v1DiscontinueThisClaim_test.js

https://tools.hmcts.net/jira/browse/CIV-15693
Unskip api tests
```
[ ] Yes
[ ] No
```

CIV-15693 Uncomment api tests for discontinue claim

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventCUI-DTSCCI-927-nonprod.json

CIV-15748
adding cru permission for claimant LR
```
[ ] Yes
[ ] No
```

CIV-15748 adding cru permission for claimant LR

---

e2e/fixtures/events/1v2DifferentSolicitorEvents/acknowledgeClaim_Solicitor1.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/acknowledgeClaim_Solicitor2.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/defendantResponse_Solicitor1.js
e2e/fixtures/events/1v2DifferentSolicitorEvents/defendantResponse_Solicitor2.js
e2e/fixtures/events/1v2SameSolicitorEvents/defendantResponse_sameSolicitor.js
e2e/fixtures/events/2v1Events/acknowledgeClaim_2v1.js
e2e/fixtures/events/2v1Events/defendantResponse_2v1.js
e2e/fixtures/events/acknowledgeClaim.js
e2e/fixtures/events/defendantResponse.js

civil service pr https://github.com/hmcts/civil-service/pull/5848

CIV-0000 add missing partyids

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-GA-CUI-nonprod.json
ccd-definition/CaseField/CaseFieldGAspec-GA-CUI-nonprod.json
ccd-definition/ComplexTypes/GeneralApplicationGAspec-GA-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15650
Add new fields for judge orders and reasons
```
[ ] Yes
[x] No
```

CIV-15650 Add new fields for judge orders and reasons

---

ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-15901
Removing character validation limit from email on ga hearing details 
```
[ ] Yes
[ ] No
```

CIV-15901 Removing Email Character Validation

---

e2e/tests/api_tests/sdo_R2/api_noise_induced_hearing_loss_test.js

DTSCCI-000
disable test to run in prod
```
[ ] Yes
[ ] No
```

DTSCCI-000 disable test to run in prod

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-caseworkerEvents-nonprod.json
ccd-definition/CaseEventToFields/FlagCase-caseworkerEvents-nonprod.json
ccd-definition/CaseField/CaseField-caseworkerEvents-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15868
```
[ ] Yes
[ x ] No
```

CIV-15868 COR all final orders screen

---

e2e/tests/api_tests/sdo_R2/api_dispute_resolution_hearing_test.js

DTSCCI-1366
disable test to run in prod
```
[ ] Yes
[ ] No
```

DTSCCI-1366 disable test to run in prod

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-caseworkerEvents-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16357
Add authorisations that must have been accidentally overriden as part of a master merge.
```
[ ] Yes
[x] No
```

CIV-16357 - re-add authorisations for message history

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-JO-nonprod.json
ccd-definition/CaseField/CaseField-JO-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-15754
```
[ ] Yes
[ ] No
```

CIV-15754 LR JbA Live Feed

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json

- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-15985
Added permissions to the cui user
```
[ ] Yes
[x ] No
```

CIV-15985 request more info document not accessible to cui user

---

charts/civil-ccd/Chart.yaml

DTSCCI-1364 upgrade ccd chart

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json

So that we can update it via bulk retrigger instead of a change request
```
[ ] Yes
[ ] No
```

DTSCCI-000 - Update dismissed deadline auths

---

ccd-definition/CaseTypeTab/Notes-caseworkerEvents-nonprod.json
ccd-definition/ComplexTypes/StoredObligationData.json

https://tools.hmcts.net/jira/browse/CIV-15614
Add flag to storedObligationData object that was previously in obligationCollection.
```
[ ] Yes
[x] No
```

CIV-15614 - Add flag to storedObligationData object

---

e2e/api/steps.js
e2e/api/steps_LRspec.js
e2e/fixtures/events/judgmentOnline1v1Spec.js
e2e/tests/api_tests/judgmentOnline/api_judgment_online_spec_1v1_test.js
e2e/tests/api_tests/judgmentOnline/api_judgment_online_spec_1v2_test.js

CIV-15869 api tests

---

e2e/tests/api_tests/sdo_R2/api_dispute_resolution_hearing_test.js

DTSCCI-1366 enable ft

---

ccd-definition/AuthorisationCaseField/AuthorisationFinalOrders.json

https://tools.hmcts.net/jira/browse/DTSCCI-1439
Unable to request hearing or take case offline. finalOrderDocumentCollection permissions updated for system user.
```
[ ] Yes
[ ] No
```

DTSCCI-1439 Unable to request hearing or take case offline

---

e2e/tests/api_tests/sdo_R2/api_noise_induced_hearing_loss_test.js

DTSCCI-1283
enable ft
```
[ ] Yes
[ ] No
```

DTSCCI-1283 enable ft

---

sonar-project.properties

DTSCCI-1283 fix sonar issue

---

e2e/tests/api_tests/judgmentOnline/api_judgment_online_spec_1v2_test.js

https://tools.hmcts.net/jira/browse/CIV-16299
Fix api test
```
[ ] Yes
[ ] No
```

CIV-0000 Fix DJ Set Aside API Test

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16443
Give defendant access to request for info doc
```
[ ] Yes
[x] No
```

CIV-16443 Give defendant access to request for info doc

---

ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json

https://tools.hmcts.net/jira/browse/CIV-16376
Refactored regex to accept + char in email Id
```
[ ] Yes
[x] No
```

CIV-16376 - Special characters cannot be inputted for email addresses - contact information

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-R2-CUI-nonprod.json
ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
e2e/api/steps.js

Gareth40343 patch 1

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-FixedCosts-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-FixedCosts.json
ccd-definition/CaseField/CaseFieldLRspec-FixedCosts-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-FixedCosts.json

- Move olddjscreen field to base file
```
[ ] Yes
[ ] No
```

CIV-0000 Move olddjscreen field to base file

---

charts/civil-ccd/values.preview.template.yaml

DTSCCI-949 Reinstate civil service image to latest

---

e2e/tests/api_tests/defaultJudgments/api_dj_spec_1v1_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_spec_1v2_test.js
e2e/tests/api_tests/defaultJudgments/api_dj_spec_2v1_test.js
e2e/tests/ui_tests/default_judgement/1v1specDJ_test.js
e2e/tests/ui_tests/default_judgement/1v2specDJ_test.js

DTSCCI-000 Enable Spec DJ Tests in Prod

---

e2e/api/steps.js

- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[x ] No
```

CIV-16322 e2e test fix for CIV-16322

---

ccd-definition/CaseEvent/User/UserEvents-caseworkerEvents-nonprod.json

PR for https://tools.hmcts.net/jira/browse/CIV-16559

CIV-16559 Publish Confirm_Order_Review Event to WA

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json

DTSCCI-000 allowing applicantDeadline to be updated on retrigger

---

playwright-e2e/actions/ui/exui/claimant-solicitor/create-claim-spec-actions.ts
playwright-e2e/actions/ui/exui/claimant-solicitor/create-claim/create-claim-spec-actions.ts
playwright-e2e/actions/ui/exui/defendant-solicitor/defendant-response/defendant-response-actions.ts
playwright-e2e/pages/exui/claimant-defendant-solicitor/add-defendant-litigation-friend/unspec/confirm-add-defendant-litigation-friend/confirm-add-defendant-litigation-friend-page.ts
playwright-e2e/pages/exui/claimant-defendant-solicitor/inform-agreed-extension-date/lr-spec/confirm-inform-agreed-extension-date-spec/confirm-inform-agreed-extension-date-spec-page.ts
playwright-e2e/requests/civil-service-requests.ts
playwright-e2e/steps/ui/exui/exui-dashboard-steps.ts

DTSCCI-000 Add Missing AllMethodsSteps to classes

---

ccd-definition/CaseEvent/User/UserEvents-amendBundle.json

DTSCCI-1239 Allow manage documents event to be run in all case states

---

playwright-e2e/tests/unspec/fast-track-1v1.spec.ts

DTSCCI-000 Fix Playwright Tests

---

src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java

DTSCCI-1721 wa system user security classification to restricted

---

e2e/api/steps_LRspec.js
e2e/fixtures/events/discontinueClaimSpec.js

Fix api test failure realted to https://github.com/hmcts/civil-ccd-definition/pull/5375/files
```
[ ] Yes
[ ] No
```

CIV-0000 Fix CIV-16600 test failure

---

charts/civil-ccd/Chart.yaml

DTSCCI-1691 bump deprecated service bus chart

---

ccd-definition/AuthorisationCaseField/systemUpdateLRspec-nonprod.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec-prod.json
ccd-definition/AuthorisationCaseField/systemUpdateLRspec.json

4 pertest xx
```
[ ] Yes
[ ] No
```

DTSCCI-0000 - respondToClaimAdmitPartLRspec CRUD Access

---

ccd-definition/CaseEvent/Camunda/BusinessProcessEvents.json

DTSCCI-1699 removing duplicate prod

---

ccd-definition/CaseEvent/Camunda/BusinessProcessEvents-R2-CUI.json

DTSCCI-1699 fix lip

---

charts/civil-ccd/values.preview.template.yaml

DTSCCI-0000 - disable sb

---

charts/civil-ccd/Chart.yaml

DTSCCI-1891 upgrade wa chart

---

ccd-definition/CaseEvent/User/UserEvents-SDO.json
charts/civil-ccd/values.preview.template.yaml
e2e/tests/ui_tests/settle_discontinue/1v2DiscontinueThisClaim_test.js

DTSCCI-1738 avoid bypass ongoing process

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.aat.template.yaml
charts/civil-ccd/values.preview.template.yaml
charts/civil-ccd/values.yaml

DTSCCI-000 - fix master

---

Jenkinsfile_nightly
playwright.config.ts

There are 18 codecept js tests out of which 16 are disabled and 2 are failing. They are running in functional tests stage in Jenkins and failing the nightly pipeline, I've commented them out as they are not testing anything anyway
```
[ ] Yes
[X] No
```

DTSCCI-1888 Fix nightly pipeline

---

ccd-definition/AuthorisationCaseEvent/systemUpdate.json
ccd-definition/CaseEvent/Camunda/RetriggerCase.json
ccd-definition/CaseEventToFields/RetriggerSpec.json

DTSCCI-000 - Add retrigger event for Mediation Unsuccessful

---

build.gradle

CIV-00000 update befta-fw 9.2.3

---

e2e/tests/api_tests/damages/api_noc_unspec_test.js
e2e/tests/api_tests/mediation/api_1v1_spec_small_mediation_documents_upload_test.js

DTSCCI-2063 disable FT temp

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-WelshEnhancements-nonprod.json
ccd-definition/CaseField/CaseField-WelshEnhancements-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16832
New collection to store SDO pre-translation
```
[ ] Yes
[x] No
```

CIV-16832 New collection to store SDO pre-translation

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-WelshEnhancements-nonprod.json
ccd-definition/CaseField/CaseField-WelshEnhancements-nonprod.json
ccd-definition/FixedLists/WelshEnhancements/DocumentType-nonprod.json
ccd-definition/FixedLists/WelshEnhancements/TranslatedDocumentType-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16856
Add new doc types for translated SDO
```
[ ] Yes
[x] No
```

CIV-16856 Add new doc types for translated SDO

---

ccd-definition/CaseEventToFields/WorkAllocationIntegrationFields-CUI-Welsh-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16888
Publishing fields for work allocation
```
[ ] Yes
[x] No
```

CIV-16888 - Work allocation for english to welsh responses

---

bin/build-release-ccd-definition.sh

CIV-17066 unshutter prod

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-CUI.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-system-field-reader.json
ccd-definition/CaseField/CaseField-CUI.json

https://tools.hmcts.net/jira/browse/CIV-16980
```
[ ] Yes
[ ] No
```

CIV-16980 Defendant Lip statement of truth 

---

package.json
yarn.lock

DTSCCI-000 Remove Playwright Package

---

ccd-definition/CaseField/CaseField-SettleDiscontinue-nonprod.json
ccd-definition/FixedLists/DiscontinuanceTypeList-DiscontinueClaim.json
ccd-definition/FixedLists/WelshEnhancements/DiscontinuanceTypeList-DiscontinueClaim-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-16858
Move fixed list item to nonprod file
```
[ ] Yes
[x] No
```

CIV-16858 Move fixed list item to nonprod file

---

e2e/api/testingSupport.js
playwright-e2e/base/base-page.ts
playwright-e2e/config/config.ts
playwright-e2e/pages/exui/claimant-defendant-solicitor/response/defendant-response/lr-spec/respondent-checklist/respondent-checklist-content.ts
playwright-e2e/pages/exui/claimant-defendant-solicitor/response/defendant-response/lr-spec/respondent-checklist/respondent-checklist-page.ts
playwright-e2e/pages/exui/exui-dashboard/case-details/case-details-page.ts
playwright-e2e/requests/civil-service-requests.ts

DTSCCI-000 Fix Playwright Tests And Reduce WaitForFinishedBusinessProcess Attempts

---

e2e/pages/queriesTab.page.js
e2e/tests/api_tests/damages/api_1v2_same_solicitor_test.js
e2e/tests/api_tests/lrspec_cui/api_1v1_spec_cui_test.js
e2e/tests/ui_tests/query_management/qm_Hearing_spec_LR_test.js
e2e/tests/ui_tests/query_management/qm_followUp__spec_LR_test.js
e2e/tests/ui_tests/query_management/qm_nonHearing_spec_LR_test.js

https://tools.hmcts.net/jira/browse/CIV-17244

CIV-17244 Moved UI and API QM tests

---

charts/civil-ccd/Chart.yaml
charts/civil-ccd/values.preview.template.yaml

DTSCCI-2265
update chart to use oci endpoint
```
[ ] Yes
[ ] No
```

DTSCCI-2265 update chart to use oci endpoint

---

ccd-definition/CaseEvent/User/UserEventsDJ.json
e2e/api/steps.js

Reverts hmcts/civil-ccd-definition#5796

DTSCCI-2074 revert Update state of dj event

---

ccd-definition/AuthorisationCaseState/AuthorisationCaseState-CUI-CP.json
ccd-definition/AuthorisationCaseState/AuthorisationCaseState-settleDiscontinue-nonprod.json

DTSCCI-2041 fix incorrect state permission

---

ccd-definition/CaseEventToFields/RequestJudgementByAdmissionLRspec-CUI-LRA-Bulk-nonprod.json
ccd-definition/CaseEventToFields/RequestJudgementByAdmissionLRspec-CUI-LRA-Bulk-prod.json
ccd-definition/CaseEventToFields/RequestJudgementByAdmissionLRspec-CUI.json

https://tools.hmcts.net/jira/browse/CIV-17261
```
[ ] Yes
[ ] No
```

CIV-17261 Request JBA event - fixed costs at judgment

---

.github/workflows/ado_artifacts_build.yml
build.gradle

DTSCCI-2086 swtich from jitpack config

---

charts/civil-ccd/values.preview.template.yaml

DTSCCI-2345 - disable service bus

---

e2e/tests/ui_tests/query_management/qm_nonHearing_spec_LR_test.js

DTSCCI-000 Fix Flaky Nightly Test

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-WelshEnhancements-nonprod.json
ccd-definition/CaseEventToFields/WorkAllocationIntegrationFields-CUI-Welsh-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17454
```
[ ] Yes
[x] No
```

CIV-17454 - fix page order

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-LRA-Bulk-nonprod.json
ccd-definition/CaseEventToFields/DefendantResponseAdmitPartLRspec-LRA-Bulk-nonprod.json
ccd-definition/CaseEventToFields/DefendantResponseLrSpec-LRA-Bulk-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-LRA-Bulk-nonprod.json
ccd-definition/ComplexTypes/RespondToClaimDefenceLRspec-LRA-Bulk-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17360
Extra fields as string versions
```
[ ] Yes
[x] No
```

CIV-17360 - Extra fields as strings to display formatted decimals for them

---

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-LRA-Bulk-nonprod.json
ccd-definition/AuthorisationCaseField/AuthorisationCaseField-system-field-reader-LRA-Bulk-nonprod.json
ccd-definition/CaseEventToFields/DefendantResponseAdmitPartLRspec-LRA-Bulk-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-CUI-LRA-Bulk-nonprod.json
ccd-definition/CaseField/CaseFieldLRspec-LRA-Bulk-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17460
Part Admit  pay immediately - Static text updates in defendant /claimant journey
```
[ ] Yes
[ ] No
```

CIV-17460 Part Admit pay immediately - Static text updates

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-WelshEnhancements-nonprod.json
ccd-definition/CaseEvent/Camunda/CaseEvents-WelshEnhancements-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17437
Event for removing DJ notification
```
[ ] Yes
[x] No
```

CIV-17437 Event for removing DJ notification

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-CUI-Welsh-nonprod.json
ccd-definition/CaseEvent/User/UserEventsLRspec-CUI.json

- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-17438
WLU user cannot see the claimant intention events on the event history
```
[ ] Yes
[x ] No
```

CIV-17438 modified show event notes for the claimant response spec

---

ccd-definition/AuthorisationCaseState/AuthorisationCaseState-CUI-CP.json

https://tools.hmcts.net/jira/browse/DTSCCI-2515

DTSCCI-2515 Respondent LR should also have access to decision outcome state

---

bin/add-org-roles-to-users.sh
ccd-definition/AuthorisationCaseField/QueryManagement-PublicQueries-nonprod.json
ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-CUI-Welsh-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17456
https://tools.hmcts.net/jira/browse/CIV-17457
https://tools.hmcts.net/jira/browse/CIV-17458
wlu admin roles 
```
[ ] Yes
[ ] No
```

CIV-17456 added wlu admin roles

---

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-WelshEnhancements-nonprod.json
ccd-definition/CaseEvent/Camunda/CaseEvents-WelshEnhancements-nonprod.json

https://tools.hmcts.net/jira/browse/CIV-17524
Add new event for resetting language
```
[ ] Yes
[x] No
```

CIV-17524 Add new event for resetting language

---

Jenkinsfile_CNP

CIV-00000 Test PR

---

Jenkinsfile_CNP

CIV-0000 run function test

---

ccd-definition/AuthorisationCaseEvent/systemUpdate.json
ccd-definition/AuthorisationCaseField/systemUpdate.json

DTSCCI-000 adding system permission to refer to judge event

---

bin/build-release-ccd-definition.sh

CIV-0000 Unshuttering xui

---

e2e/api/steps_LRspecSmall.js
e2e/tests/api_tests/sdo_R2/api_request_for_reconsideration_test.js

DTSCCI-000 Fix Civil Service Nightly

---

ccd-definition/AuthorisationCaseEvent/systemUpdate-JO.json
ccd-definition/CaseEvent/Camunda/BusinessProcessEvents-JO.json
ccd-definition/CaseEvent/Camunda/DashboardEvents-JO.json

https://tools.hmcts.net/jira/browse/DTSCCI-2366
```
[ ] Yes
[X] No
```

DTSCCI-2366 revert CIV-17556 changes

---

ccd-definition/CaseField/CaseField-WelshEnhancements-nonprod.json
ccd-definition/CaseField/CaseField-WelshEnhancements-prod.json
ccd-definition/CaseField/CaseField.json

CIV-0000 - Added a field to prod file for CUI welsh release.

---

bin/build-release-ccd-definition.sh

CIV-0000 Unchutter CCD def
