hmcts/civil-ccd-definition

ccd-definition/CaseEventToFields/ClaimantResponse.json, ccd-definition/CaseEventToFields/DefendantResponse.json
https://tools.hmcts.net/jira/browse/CMC-1589
Small claims show hide condition was removed in CMC-1160. Added back.
```
[ ] Yes
[x] No
```
=> fix: hide disclosure of non elec docs when small claim in dq (CMC-1589)

ccd-definition/CaseEventToFields/CreateClaim.json
https://tools.hmcts.net/jira/browse/CMC-1323
Add empty check for boolean field
```
[ ] Yes
[x] No
```
=> fix: empty check for pba accounts boolean field (CMC-1323)

ccd-definition/CaseEventToComplexTypes/AddDefendantLitigationFriend.json, ccd-definition/ComplexTypes/LitigationFriend.json, e2e/fragments/litigationFriend.js
https://tools.hmcts.net/jira/browse/CMC-1596
- using `DocumentOrImageWithRegex` to validate file input
- amended e2e test to account for change to field type
```
[ ] Yes
[x] No
```
=> fix : adding regex validation to certificate of suitability in litigation friend event (CMC-1596) (2/5)

ccd-definition/CaseEventToComplexTypes/AddDefendantLitigationFriend.json, ccd-definition/ComplexTypes/LitigationFriend.json, e2e/fragments/litigationFriend.js
https://tools.hmcts.net/jira/browse/CMC-1596
- using the original `certificateOfSuitability` field, removing the `certificateOfSuitabilityNew` field
```
[ ] Yes
[x] No
```
=> fix : use original certificateOfSuitability field (CMC-1596) (4/5)

Jenkinsfile_CNP, bin/build-release-ccd-definition.sh
All `-nonprod.json` files are now excluded on all environments by default. This is to ensure that we deploy and test production definition.
```
[ ] Yes
[x] No
```
=> build: excluded -nonprod.json files from definition on all envs

e2e/api/steps.js
https://tools.hmcts.net/jira/browse/CMC-1486
Small change to the chai config to allow for more readable test logging. 
Example (before):
Running ````assert.deepEqual(responseBody.data, 'test')````
````
1) CCD API tests @api-tests
Create claim:
AssertionError: expected { Object (solicitorReferences) } to deeply equal 'test'
````
(After the change):
````
1) CCD API tests @api-tests
Create claim:
AssertionError: expected { solicitorReferences: 
{ applicantSolicitor1Reference: 'Applicant reference',
respondentSolicitor1Reference: 'Respondent reference' } } to deeply equal 'test'
````
```
[ ] Yes
[x] No
```
=> fix: allow for more readable test logging (CMC-1486)

bin/pull-latest-release-asset.sh
https://tools.hmcts.net/jira/browse/CMC-1688
The fix for this was changed when it was found that the reason the script fails was because the GitHub API calls were being rate limited
`{"message":"API rate limit exceeded for 20.50.109.148. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`
Adding an authentication token to the API call increases the rate limit
```
[ ] Yes
[x] No
```
=> fix: Add authentication to pull-latest-release-asset.sh (CMC-1688)

e2e/helpers/browser_helper.js
n/a
add await to runAccessibility method.
Should solve following error:
```
[2021-06-29T15:15:24.485Z] (node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addScriptTag' of undefined
[2021-06-29T15:15:24.485Z]     at runAccessibility (/opt/jenkins/workspace/ghtly_Civil_civil-service_master/e2e/helpers/accessibility/runner.js:19:14)
[2021-06-29T15:15:24.485Z]     at BrowserHelpers.runAccessibilityTest (/opt/jenkins/workspace/ghtly_Civil_civil-service_master/e2e/helpers/browser_helper.js:60:5)
[2021-06-29T15:15:24.485Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-06-29T15:15:24.485Z]     at async Object.enterLitigantFriendWithDifferentAddressToApplicant (/opt/jenkins/workspace/ghtly_Civil_civil-service_master/e2e/pages/createClaim/ …
```
=> fix: wait for promise to resolve on runAccessibility method

e2e/helpers/browser_helper.js
Reverts hmcts/civil-ccd-definition#143
All crossbrowser tests now failing due to 
```
06:46:23    1) End-to-end journey @cross-browser-tests
06:46:23         Full end-to-end journey:
06:46:23       Cannot read property 'addScriptTag' of undefined
```
=> Revert "fix: wait for promise to resolve on runAccessibility method"

codecept.conf.js
https://tools.hmcts.net/jira/browse/CMC-1700
`sauce_labs_reporting_helper.js` was causing an error when running the e2e tests since it doesn't account for using Puppeteer instead of WebDriver. This stopped screenshots from being taken on test failures. 
Sauce Labs is only used in nightly crossbrowser tests which uses a different config `saucelabs.conf.js` so can be safely removed from the default config.
```
[ ] Yes
[x] No
```
=> fix: E2E failures screenshotted (CMC-1700)

build.gradle
n/a
bump commons compress
```
[ ] Yes
[x] No
```
=> fix: bump befta-fw from 8.2 -> 8.3 and commons compress from 1.18 to 1.21

ccd-definition/CaseField/CaseField.json, ccd-definition/CaseTypeTab/ClaimDetails.json
https://tools.hmcts.net/jira/browse/CMC-1845
- Adding the `respondent2OrganisationPolicy` Field on the ClaimDetails page
- Updating label for this field to be consistent with `respondent1OrganisationPolicy`
```
[ ] Yes
[x] No
```
=> feat/CMC-1845: Show Respondent 2 Org on Claim Details Tab

ccd-definition/CaseEvent/User/UserEvents.json
https://tools.hmcts.net/jira/browse/CMC-1520
Change from v1 callback for about-to-submit, acknowledge claim to just about-to-submit (no version)
Linked to -> https://github.com/hmcts/civil-service/pull/572  (Freeing up the V1 callback)
```
[ ] Yes
[X] No
```
=> CMC-1520: Remove-V_1_about-to-start-acknowledge-claim

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-SDO-nonprod.json, ccd-definition/CaseEvent/Camunda/NotificationEvents-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-861
This PR creates a new ccd event (`NOTIFY_PARTIES_SDO_TRIGGERED`) representing the event to notify relevant parties that an SDO has been triggered on a case. It has a callback that will be handled by a handler in a future PR.
There will be two event authorizations for now as the file that the event was created in has been created in a [previous PR](https://github.com/hmcts/civil-ccd-definition/pull/334/files) that is not merged in yet due to pipeline issues, once that has been merged in the changes compared to Master should be just the new event authorization entry.
```
[ ] Yes
[x] No
```
=> CIV-861: Add email notify sdo event

src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
To resolve our pipeline issues as recommended under https://tools.hmcts.net/jira/browse/CFTS-2045 making following changes:
1. Removing the override of shouldTolerateDataSetupFailure method to true so that if high level data setup fails we don't see a green but a red.
2. Overriding createRoleAssignments to do nothing to remove the red herring:
"Caused by: java.lang.NullPointerException: Environment variable `ROLE_ASSIGNMENT_USER_PASSWORD` is required"
```
[ ] Yes
[x ] No
```
=> resolving role assignment error on pipeline

ccd-definition/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/CMC-1884
The hint text from from defendant solicitor 1 and 2 search pages has been removed in CaseField.json
```
[ ] Yes
[ x] No
```
=> feat: remove hint text from defendant solicitor 1 and 2 search pages

ccd-definition/CaseEvent/User/UserEvents-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-869
For the AC's to be met within the above ticket, these callbacks need to be added to the ccd event. This should've been done in a [previous PR](https://github.com/hmcts/civil-ccd-definition/pull/540) which contained the changes for [this ticket](https://tools.hmcts.net/jira/browse/CIV-861) which is where the changes in this PR should have realistically been.
This is a straightforward PR and none of the previous changes without the changes in this PR have cause any issues or introduce any broken code. 
```
[ ] Yes
[x] No
```
=> CIV-866 adds callback for CREATE_SDO event

charts/civil-ccd/Chart.yaml
- Bump java charts to v3.7.2
- Bump camunda-bpm to 0.0.23
N/A
```
[ ] Yes
[x] No
```
=> build/bump-charts: Update java charts to v3.7.2

ccd-definition/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/CMC-1950
Constrain the Defendant 2 reference field length to same as defendant 1 and claimant reference
```
[ ] Yes
[x] No
```
=> feat: restrict defendant 2 reference field length

Jenkinsfile_CNP, build.gradle, e2e/steps_file.js, e2e/tests/1v1Journey_test.js, e2e/tests/api_1v1_test.js, e2e/tests/api_multiparty/api_1v2_different_solicitor_test.js, e2e/tests/api_multiparty/api_1v2_same_solicitor_test.js, e2e/tests/api_multiparty/api_2v1_test.js, e2e/tests/multiparty/1v2CreateClaim_test.js, e2e/tests/multiparty/1v2DiffSolJourney_test.js, e2e/tests/multiparty/1v2SameSolJourney_test.js, e2e/tests/multiparty/2v1Journey_test.js, package.json
With this Pr change -->C ivil ccd defintion deployed helm resources will be deleted by default on successful PR.
If anyone wants to retain helm release for testing they have to add a label "enableHelm" It is already added to labels list.
See below screenshot for reference
=> [Improvements] - Only when enableHelm label added then Helm Release will be retained 

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CMC-1957
- Removed redundant cve suppressions
- Temporarily suppressed three new dependency issues:
- Spring security - CVE-2021-22112 - HIGH
- jquery- CVE-2020-11022, CVE-2020-11023 - MEDIUM
=> Removed cve redundant suppressions

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-SDO-nonprod.json, ccd-definition/CaseEvent/Camunda/NotificationEvents-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-1376
This PR adds new notification events within CCD to be used by Camunda in the `CREATE_SDO` journey.
The reason a second event isn't needed for the applicant solicitor is because the applicants within this journey will always have the same legal rep and therefore the same solicitor.
```
[ ] Yes
[x] No
```
=> update sdo notification events for multiparty

ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json, ccd-definition/CaseEventToFields/CreateSDO-SDO-nonprod.json, ccd-definition/CaseField/CaseField-SDO-nonprod.json, ccd-definition/FixedLists/DrawDirectionsOrderSmallClaimsAdditionalDirections-SDO-nonprod.json, ccd-definition/FixedLists/OrderTypeTrialAdditionalDirections-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-1430
https://tools.hmcts.net/jira/browse/CIV-1431
This PR adds additional directions to some of the screens within the SDO flow.
```
[ ] Yes
[x] No
```
=> add additional directions options

ccd-definition/AuthorisationCaseEvent/systemUpdate.json, ccd-definition/CaseEvent/Camunda/NotificationEvents.json
https://tools.hmcts.net/jira/browse/CMC-2033
- Added NOTIFY_RESPONDENT_SOLICITOR2_FOR_CASE_TAKEN_OFFLINE notification event
```
[ ] Yes
[X] No
```
=> Case Taken Offline Schedular enhanced to cater for multiparty 1 v 2 (2 defendant solicitors)

ccd-definition/AuthorisationCaseField/systemUpdateLRspec.json
made respondent2ClaimResponseTypeForSpec available to Camunda, so it can access it on external tasks
```
[ ] Yes
[X] No
```
=> fix/NO-ISSUE 

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json, ccd-definition/AuthorisationCaseField/staff.json, ccd-definition/AuthorisationCaseField/systemUpdate.json, ccd-definition/CaseField/CaseField.json, e2e/tests/api_tests/damages/api_1v1_test.js
https://tools.hmcts.net/jira/browse/CIV-1879
Litigant in person / defendant defending themselves would not go offline
Changes for scheduler to take the case offline is going to be built in CIV-2090
Changes for camunda: https://github.com/hmcts/civil-camunda-bpmn-definition/pull/193
Changes for service: https://github.com/hmcts/civil-service/pull/954
```
[ ] Yes
[ x] No
```
=> feat/CIV-1879 LiP stays online following create claim

build.gradle, config/owasp/suppressions.xml
updated the versions of 2 dependencies to the nearest point they don't fail the check; suppressed another vulnerability because there is not a better version available yet.
```
[ ] Yes
[X] No
```
=> fix/CVE-2022-22978 and CVE-2020-0187

ccd-definition/CaseEventToComplexTypes/CreateSDO-SDO-nonprod.json, ccd-definition/CaseEventToFields/CreateSDO-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-3209
Fixes a bug where pressing previous didn't go to the previous screen but rather the screen before. This was because the previous screen was conditionally rendered but the value used for this condition was not being retained in case data.
```
[ ] Yes
[x] No
```
=> Civ 3209 sdo previous page bug new

README.md, ccd-definition/AuthorisationCaseField/AuthorisationCaseField-SDO-nonprod.json, ccd-definition/CaseEventToComplexTypes/CreateSDO-SDO-nonprod.json, ccd-definition/CaseEventToFields/CreateSDO-SDO-nonprod.json, ccd-definition/CaseField/CaseField-SDO-nonprod.json, ccd-definition/ComplexTypes/FastTrackTrial-SDO-nonprod.json, ccd-definition/ComplexTypes/SdoOrderDocument-sdo-nonprod.json, ccd-definition/FixedLists/FastTrackTrialBundleType-SDO-nonprod.json, ccd-definition/FixedLists/SmallClaimsTimeEstimate-SDO-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-2093
This PR updates small claims hearing to include more options as well as adds the callbacks to generate the pdfs for the SDO journey.
```
[ ] Yes
[x] No
```
=> Generate sdo pdfs final

charts/civil-ccd/values.aat.template.yaml, charts/civil-ccd/values.preview.template.yaml
No user profiles are created by this, but causes unnecessary flakiness 
https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_a_to_c%2Fcivil-ccd-definition/detail/PR-1309/34/pipeline 
```
[ ] Yes
[ ] No
```
=> Disable unused user profile importer

config/owasp/suppressions.xml
[civil-ccd-definition] - Fix for CVE-2021-22118 and  CVE-2021-42550
https://tools.hmcts.net/jira/browse/CIV-4849
https://tools.hmcts.net/jira/browse/CIV-4850
[civil-ccd-definition] - Fix for CVE-2021-22118 and  CVE-2021-42550
```
[ ] Yes
[x ] No
```
=> removed CVE-2021-22118 from suppression file

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-4851
- Removed the suppression CVE-2022-22950
- Spring dependencies are already updated, so no change there.
```
[ ] Yes
[ ] No
```
=> CIV-4851: remove CVE-2022-22950

src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
It is defaulted to false https://github.com/hmcts/befta-fw/blob/master/src/main/java/uk/gov/hmcts/befta/dse/ccd/DataLoaderToDefinitionStore.java#L178, this helps fixing issue on demo pipeline where pipeline fails when there is a timeout.
```
[ ] Yes
[x] No
```
=> Tolerate data setup failure

e2e/api/steps.js
- removing hearing error check to aid in merging 
- https://github.com/hmcts/civil-ccd-definition/pull/1828
- https://github.com/hmcts/civil-service/pull/1945/files
```
[ ] Yes
[x] No
```
=> temporarily removing hearing error check

ccd-definition/AuthorisationCaseField/AuthorisationCaseField.json, config/owasp/suppressions.xml
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
This is the bug that was identified while testing in demo environment. At the time of task configuration, The Civil DMN evaluated the region as null even though the it is present in CaseData. It was identified that caseworker-civil-systemupdate permission was missed on caseManagementLocation casefield
```
[ ] Yes
[ x] No
```
=> added missing permissions to caseManagementLocation casefield

e2e/config.js
CIV-5378
set environment back to env variable instead of hardcoded 'preview'
```
[ ] Yes
[X] No
```
=> CIV-5378 removed hardcoded preview environment

bin/utils/process-definition.sh
Using dbyccu version of definition processor tille latest is fixed
```
[ ] Yes
[ ] No
```
=> CIV-0000 - Using dbyccu version of definition processor till latest is fixed

bin/create-github-release.sh
N/A
Re-instates the civil-screenshots.zip file for AAT functional test runs.
The file was temporarily disabled as it was being produced against the wrong directory. This should rectify the issue.
```
[ ] Yes
[x] No
```
=> CIV-TASK Re-instate civil-screenshots.zip in AAT

ccd-definition/FixedLists/PbaNumber.json, e2e/api/steps.js, e2e/api/steps_LRspec.js, e2e/fixtures/events/createClaim.js, e2e/fixtures/events/createClaimSpec.js, e2e/fixtures/events/createClaimSpecFast.js, e2e/fixtures/events/createClaimSpecSmall.js, e2e/fixtures/events/resubmitClaim.js, e2e/run-functional-tests.sh
Payments team uses dummy pba account PBAFUNC12345 so that it wont call liberata for any verification. So they have suggested us to use this in api calls instead of real account that saves a lot of calls to liberata and 504 errors. This is not effective in end to end tests. Its only for api calls.
I have tested both end to end tests and api tests of my changes in https://github.com/hmcts/civil-service/pull/2838 
This does need some change in civil-sdk to be made to run the tests locally
=> CIV-0000 Mitigate ValidateClaimFee failure with  pba account PBAFUNC12345 (provided by payments for api calls)

ccd-definition/AuthorisationCaseField/AuthorisationFinalOrders-nonprod.json
Cost title not showing in demo, have added authorisations for casefields finalOrderCost and finalOrderCostSecondaryLabel
https://tools.hmcts.net/jira/browse/CIV-10836
```
[ ] Yes
[ x] No
```
=> CIV-10836 asssisted order cost bug

ccd-definition/CaseTypeTab/Hearings-prod.json
fix to show tab when hearing notes exist
```
[ ] Yes
[ x] No
```
=> CIV-0000 fix to show tab when hearing notes exist

ccd-definition/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/CIV-13363
Fixed the casefields used in the listing notes tab to use the label Claimant instead of Applicant.
```
[ ] Yes
[ X] No
```
=> CIV-13363 Fix listing notes tab labels

ccd-definition/CaseEventToComplexTypes/CreateSDO-SDO.json
https://tools.hmcts.net/jira/browse/CIV-15269
Make date field mandatory for SDO, so no blanks in document 
```
[ ] Yes
[ x] No
```
=> CIV-15269 Make dates mandatory sdo

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldLRspec.json
- Added judge read permissions to respondent1ClaimResponseTypeForSpec respondent2ClaimResponseTypeForSpec so they can have access to the listing notes tab on spec claims as its failed a tab show condition.
```
[X] Yes
[ ] No
```
=> CIV-0000 Fix judge not able to see listing notes tab

ccd-definition/ComplexTypes/StoredObligationData.json
https://tools.hmcts.net/jira/browse/CIV-15614
Make obligationDate searchable again for WA
```
[ ] Yes
[x] No
```
=> CIV-15614 - Fix that makes obligationDate searchable in storedObligationDate

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEvent-LipVsLr-nonprod.json, ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventLRspec-R2-CUI.json, ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventLRspec.json
https://tools.hmcts.net/jira/browse/DTSCCI-2439
As the events are hidden in the history the users are not seeing the claim in awaiting def response state,
=> DTSCCI-2439 Update permissions to view awaiting def response state
